/**
 * Legacy free-text make strings → canonical English make name.
 * Used for migration / filter normalization. Unmatched → MANUAL_REVIEW.
 * Prefer catalog make.aliases when present; this map covers common free-text.
 */
export const VEHICLE_MAKE_ALIASES: Record<string, string> = {
  mercedes: "Mercedes-Benz",
  "mercedes benz": "Mercedes-Benz",
  "mercedes-benz": "Mercedes-Benz",
  benz: "Mercedes-Benz",
  amg: "Mercedes-Benz",
  maybach: "Mercedes-Benz",
  "mercedes-maybach": "Mercedes-Benz",
  "mercedes maybach": "Mercedes-Benz",
  bmw: "BMW",
  "b m w": "BMW",
  "بي ام دبليو": "BMW",
  "بي إم دبليو": "BMW",
  مرسيدس: "Mercedes-Benz",
  "مرسيدس بنز": "Mercedes-Benz",
  مايباخ: "Mercedes-Benz",
  "مرسيدس مايباخ": "Mercedes-Benz",
  تويوتا: "Toyota",
  toyota: "Toyota",
  نيسان: "Nissan",
  nissan: "Nissan",
  هوندا: "Honda",
  honda: "Honda",
  لكزس: "Lexus",
  lexus: "Lexus",
  أودي: "Audi",
  audi: "Audi",
  بورش: "Porsche",
  porsche: "Porsche",
  // Range Rover is a Land Rover model family — not a separate make.
  "رنج روفر": "Land Rover",
  "رينج روفر": "Land Rover",
  "range rover": "Land Rover",
  rangerover: "Land Rover",
  "لاند روفر": "Land Rover",
  "land rover": "Land Rover",
  landrover: "Land Rover",
  جيب: "Jeep",
  jeep: "Jeep",
  فورد: "Ford",
  ford: "Ford",
  شيفروليه: "Chevrolet",
  chevrolet: "Chevrolet",
  chevy: "Chevrolet",
  "جي إم سي": "GMC",
  gmc: "GMC",
  هيونداي: "Hyundai",
  hyundai: "Hyundai",
  كيا: "Kia",
  kia: "Kia",
  مازدا: "Mazda",
  mazda: "Mazda",
  ميتسوبيشي: "Mitsubishi",
  mitsubishi: "Mitsubishi",
  "فولكس واجن": "Volkswagen",
  volkswagen: "Volkswagen",
  vw: "Volkswagen",
  فولفو: "Volvo",
  volvo: "Volvo",
  تسلا: "Tesla",
  tesla: "Tesla",
  إنفينيتي: "Infiniti",
  infiniti: "Infiniti",
  جينيسيس: "Genesis",
  genesis: "Genesis",
  سوزوكي: "Suzuki",
  suzuki: "Suzuki",
  سوبارو: "Subaru",
  subaru: "Subaru",
  دودج: "Dodge",
  dodge: "Dodge",
  جاكوار: "Jaguar",
  jaguar: "Jaguar",
  بنتلي: "Bentley",
  bentley: "Bentley",
  "رولز رويس": "Rolls-Royce",
  "rolls royce": "Rolls-Royce",
  "rolls-royce": "Rolls-Royce",
  فيراري: "Ferrari",
  ferrari: "Ferrari",
  لامبورغيني: "Lamborghini",
  lamborghini: "Lamborghini",
  مازيراتي: "Maserati",
  maserati: "Maserati",
  جيلي: "Geely",
  geely: "Geely",
  "إم جي": "MG",
  mg: "MG",
  "بي واي دي": "BYD",
  byd: "BYD",
  إيسوزو: "Isuzu",
  isuzu: "Isuzu",
  peugeot: "Peugeot",
  بيجو: "Peugeot",
  renault: "Renault",
  رينو: "Renault",
  cadillac: "Cadillac",
  كاديلاك: "Cadillac",
  mini: "MINI",
  ميني: "MINI",
  "aston martin": "Aston Martin",
  mclaren: "McLaren",
  changan: "Changan",
  شانجان: "Changan",
  haval: "Haval",
  هافال: "Haval",
  jetour: "Jetour",
  جيتور: "Jetour",
  skoda: "Skoda",
  سكودا: "Skoda",
  seat: "Seat",
  سيات: "Seat",
  cupra: "Cupra",
  كوبرا: "Cupra",
  fiat: "Fiat",
  فيات: "Fiat",
  "alfa romeo": "Alfa Romeo",
  hummer: "Hummer",
  همر: "Hummer",
  // KGM is canonical; SsangYong is legacy alias.
  ssangyong: "KGM",
  "ssang yong": "KGM",
  "سانج يونج": "KGM",
  kgm: "KGM",
  // GWM is canonical; Great Wall is legacy alias.
  "great wall": "GWM",
  "great wall motors": "GWM",
  "جريت وول": "GWM",
  gwm: "GWM",
  brabus: "BRABUS",
  برابوس: "BRABUS",
  xiaomi: "Xiaomi",
  شاومي: "Xiaomi",
  avatr: "Avatr",
  أفاتر: "Avatr",
  denza: "Denza",
  دينزا: "Denza",
  "lynk & co": "Lynk & Co",
  "lynk and co": "Lynk & Co",
  ineos: "INEOS",
  yangwang: "YangWang",
  "يانغ وانغ": "YangWang",
  aito: "AITO",
  soueast: "Soueast",
  "ساوث إيست": "Soueast",
  buick: "Buick",
  بيوك: "Buick",
  voyah: "Voyah",
  wey: "WEY",
  seres: "Seres",
  skywell: "Skywell",
  roewe: "Roewe",
  bestune: "Bestune",
  arcfox: "Arcfox",
  mhero: "MHERO",
  "m-hero": "MHERO",
  kaiyi: "Kaiyi",
  dfsk: "DFSK",
  fengon: "Fengon",
  fuso: "Fuso",
  "mitsubishi fuso": "Fuso",
  "ashok leyland": "Ashok Leyland",
  riddara: "Riddara",
  saic: "SAIC",
  zotye: "Zotye",
  aurus: "Aurus",
  jmc: "JMC",
  force: "Force",
  brilliance: "Brilliance",
  baw: "BAW",
  cmc: "CMC",
  karry: "Karry",
  zxauto: "ZXAUTO",
  "zx auto": "ZXAUTO",
  maextro: "Maextro",
  ora: "Ora",
};
