import type { ListingCondition } from "@/types";
import type { ImageFallbackCategory } from "@/shared/constants/image-fallbacks";

export type LiveCarSeed = {
  categoryId: "cars";
  imageCategory: ImageFallbackCategory;
  title: string;
  titleEnglish: string;
  description: string;
  descriptionEnglish: string;
  subcategory: string;
  price: number;
  condition: ListingCondition;
  features: string[];
  featured?: boolean;
};

/** Two realistic UAE listings for every brand in CAR_BRAND_MODELS. */
export const LIVE_CARS_ALL_BRANDS: LiveCarSeed[] = [
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تويوتا Land Cruiser 2020 — مستورد",
    titleEnglish: "Toyota Land Cruiser 2020 — Imported",
    description: "تويوتا Land Cruiser 2020 مستورد، فحص شامل متوفر، جاهز للمعاينة يومياً في الإمارات.",
    descriptionEnglish: "Toyota Land Cruiser 2020 imported specs, full inspection available, ready for viewing across the UAE.",
    subcategory: "سيارات عائلية",
    price: 100600,
    condition: "excellent",
    features: ["مستورد","Land Cruiser","فحص متوفر","صيانة دورية"],
    featured: true,
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تويوتا Land Cruiser Prado 2020",
    titleEnglish: "Toyota Land Cruiser Prado 2020",
    description: "تويوتا Land Cruiser Prado 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Toyota Land Cruiser Prado 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 142400,
    condition: "used",
    features: ["خليجي","Land Cruiser Prado","جاهز للتسجيل","استخدام شخصي"],
    featured: true,
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "نيسان باترول SE 2026 — فل أوبشن",
    titleEnglish: "Nissan Patrol 2026 SE — Full Option",
    description:
      "باترول 2026 مواصفات خليجية، فل أوبشن، ضمان الوكالة ساري، عداد وكالة، بدون حوادث. جاهز للمعاينة والتسجيل في دبي.",
    descriptionEnglish:
      "2026 Nissan Patrol GCC specs, full option, active dealer warranty, agency mileage, accident-free. Ready for viewing and registration in Dubai.",
    subcategory: "سيارات عائلية",
    price: 389000,
    condition: "new",
    features: ["خليجي", "Patrol", "فل أوبشن", "ضمان وكالة", "جاهز للتسجيل"],
    featured: true,
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "نيسان Patrol 2020",
    titleEnglish: "Nissan Patrol 2020",
    description: "نيسان Patrol 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Nissan Patrol 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 126800,
    condition: "used",
    features: ["خليجي","Patrol","جاهز للتسجيل","استخدام شخصي"],
    featured: true,
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "نيسان Altima 2020",
    titleEnglish: "Nissan Altima 2020",
    description: "نيسان Altima 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Nissan Altima 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيدان",
    price: 160800,
    condition: "excellent",
    features: ["خليجي","Altima","جاهز للتسجيل","استخدام شخصي"],
    featured: true,
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هوندا Accord 2020",
    titleEnglish: "Honda Accord 2020",
    description: "هوندا Accord 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Honda Accord 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيدان",
    price: 160800,
    condition: "excellent",
    features: ["خليجي","Accord","جاهز للتسجيل","استخدام شخصي"],
    featured: true,
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هوندا Civic 2020",
    titleEnglish: "Honda Civic 2020",
    description: "هوندا Civic 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Honda Civic 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيدان",
    price: 103500,
    condition: "excellent",
    features: ["خليجي","Civic","جاهز للتسجيل","استخدام شخصي"],
    featured: true,
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس LX 2020",
    titleEnglish: "Lexus LX 2020",
    description: "لكزس LX 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Lexus LX 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 234600,
    condition: "excellent",
    features: ["خليجي","LX","جاهز للتسجيل","استخدام شخصي"],
    featured: true,
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس LX 600 2020",
    titleEnglish: "Lexus LX 600 2020",
    description: "لكزس LX 600 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Lexus LX 600 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 273800,
    condition: "new",
    features: ["خليجي","LX 600","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مرسيدس G-Class 2020",
    titleEnglish: "Mercedes-Benz G-Class 2020",
    description: "مرسيدس G-Class 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Mercedes-Benz G-Class 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "أوف رود",
    price: 275100,
    condition: "new",
    features: ["خليجي","G-Class","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مرسيدس G63 2020",
    titleEnglish: "Mercedes-Benz G63 2020",
    description: "مرسيدس G63 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Mercedes-Benz G63 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "أوف رود",
    price: 303900,
    condition: "excellent",
    features: ["خليجي","G63","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو X7 2020",
    titleEnglish: "BMW X7 2020",
    description: "بي إم دبليو X7 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "BMW X7 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 302600,
    condition: "excellent",
    features: ["خليجي","X7","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو X5 2020",
    titleEnglish: "BMW X5 2020",
    description: "بي إم دبليو X5 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "BMW X5 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 246600,
    condition: "used",
    features: ["خليجي","X5","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "أودي A3 2020",
    titleEnglish: "Audi A3 2020",
    description: "أودي A3 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Audi A3 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 246600,
    condition: "used",
    features: ["خليجي","A3","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "أودي A4 2020 — مستورد",
    titleEnglish: "Audi A4 2020 — Imported",
    description: "أودي A4 2020 مستورد، فحص شامل متوفر، جاهز للمعاينة يومياً في الإمارات.",
    descriptionEnglish: "Audi A4 2020 imported specs, full inspection available, ready for viewing across the UAE.",
    subcategory: "سيارات فاخرة",
    price: 280600,
    condition: "excellent",
    features: ["مستورد","A4","فحص متوفر","صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بورش Cayenne 2020 — مستورد",
    titleEnglish: "Porsche Cayenne 2020 — Imported",
    description: "بورش Cayenne 2020 مستورد، فحص شامل متوفر، جاهز للمعاينة يومياً في الإمارات.",
    descriptionEnglish: "Porsche Cayenne 2020 imported specs, full inspection available, ready for viewing across the UAE.",
    subcategory: "سيارات فاخرة",
    price: 287100,
    condition: "excellent",
    features: ["مستورد","Cayenne","فحص متوفر","صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بورش Macan 2020",
    titleEnglish: "Porsche Macan 2020",
    description: "بورش Macan 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Porsche Macan 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 228500,
    condition: "excellent",
    features: ["خليجي","Macan","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لاند روفر Defender 2020",
    titleEnglish: "Land Rover Defender 2020",
    description: "لاند روفر Defender 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Land Rover Defender 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "أوف رود",
    price: 232400,
    condition: "excellent",
    features: ["خليجي","Defender","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لاند روفر Discovery 2020",
    titleEnglish: "Land Rover Discovery 2020",
    description: "لاند روفر Discovery 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Land Rover Discovery 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 267700,
    condition: "new",
    features: ["خليجي","Discovery","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "رنج روفر Range Rover 2020",
    titleEnglish: "Range Rover Range Rover 2020",
    description: "رنج روفر Range Rover 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Range Rover Range Rover 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 270300,
    condition: "new",
    features: ["خليجي","Range Rover","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "رنج روفر Range Rover Sport 2020",
    titleEnglish: "Range Rover Range Rover Sport 2020",
    description: "رنج روفر Range Rover Sport 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Range Rover Range Rover Sport 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 222100,
    condition: "excellent",
    features: ["خليجي","Range Rover Sport","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جيب Wrangler 2020",
    titleEnglish: "Jeep Wrangler 2020",
    description: "جيب Wrangler 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Jeep Wrangler 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "أوف رود",
    price: 200400,
    condition: "excellent",
    features: ["خليجي","Wrangler","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جيب Grand Cherokee 2020",
    titleEnglish: "Jeep Grand Cherokee 2020",
    description: "جيب Grand Cherokee 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Jeep Grand Cherokee 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 152200,
    condition: "used",
    features: ["خليجي","Grand Cherokee","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فورد F-150 2020",
    titleEnglish: "Ford F-150 2020",
    description: "فورد F-150 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Ford F-150 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "بيك أب",
    price: 140500,
    condition: "used",
    features: ["خليجي","F-150","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فورد Mustang 2020",
    titleEnglish: "Ford Mustang 2020",
    description: "فورد Mustang 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Ford Mustang 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كهربائية",
    price: 177100,
    condition: "excellent",
    features: ["خليجي","Mustang","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "شيفروليه Tahoe 2020",
    titleEnglish: "Chevrolet Tahoe 2020",
    description: "شيفروليه Tahoe 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Chevrolet Tahoe 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 174500,
    condition: "excellent",
    features: ["خليجي","Tahoe","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "شيفروليه Suburban 2020",
    titleEnglish: "Chevrolet Suburban 2020",
    description: "شيفروليه Suburban 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Chevrolet Suburban 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 122400,
    condition: "excellent",
    features: ["خليجي","Suburban","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جي إم سي Yukon 2020",
    titleEnglish: "GMC Yukon 2020",
    description: "جي إم سي Yukon 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "GMC Yukon 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 208500,
    condition: "excellent",
    features: ["خليجي","Yukon","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جي إم سي Sierra 2020 — مستورد",
    titleEnglish: "GMC Sierra 2020 — Imported",
    description: "جي إم سي Sierra 2020 مستورد، فحص شامل متوفر، جاهز للمعاينة يومياً في الإمارات.",
    descriptionEnglish: "GMC Sierra 2020 imported specs, full inspection available, ready for viewing across the UAE.",
    subcategory: "بيك أب",
    price: 153800,
    condition: "new",
    features: ["مستورد","Sierra","فحص متوفر","صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هيونداي Tucson 2020 — مستورد",
    titleEnglish: "Hyundai Tucson 2020 — Imported",
    description: "هيونداي Tucson 2020 مستورد، فحص شامل متوفر، جاهز للمعاينة يومياً في الإمارات.",
    descriptionEnglish: "Hyundai Tucson 2020 imported specs, full inspection available, ready for viewing across the UAE.",
    subcategory: "سيارات عائلية",
    price: 118800,
    condition: "new",
    features: ["مستورد","Tucson","فحص متوفر","صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هيونداي Santa Fe 2020",
    titleEnglish: "Hyundai Santa Fe 2020",
    description: "هيونداي Santa Fe 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Hyundai Santa Fe 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 155400,
    condition: "excellent",
    features: ["خليجي","Santa Fe","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "كيا Sportage 2020",
    titleEnglish: "Kia Sportage 2020",
    description: "كيا Sportage 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Kia Sportage 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 155400,
    condition: "excellent",
    features: ["خليجي","Sportage","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "كيا Sorento 2020",
    titleEnglish: "Kia Sorento 2020",
    description: "كيا Sorento 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Kia Sorento 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 98100,
    condition: "used",
    features: ["خليجي","Sorento","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مازدا CX-5 2020",
    titleEnglish: "Mazda CX-5 2020",
    description: "مازدا CX-5 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Mazda CX-5 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 94200,
    condition: "used",
    features: ["خليجي","CX-5","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مازدا CX-9 2020",
    titleEnglish: "Mazda CX-9 2020",
    description: "مازدا CX-9 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Mazda CX-9 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 128200,
    condition: "excellent",
    features: ["خليجي","CX-9","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "ميتسوبيشي Pajero 2020",
    titleEnglish: "Mitsubishi Pajero 2020",
    description: "ميتسوبيشي Pajero 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Mitsubishi Pajero 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "أوف رود",
    price: 130800,
    condition: "excellent",
    features: ["خليجي","Pajero","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "ميتسوبيشي Outlander 2020",
    titleEnglish: "Mitsubishi Outlander 2020",
    description: "ميتسوبيشي Outlander 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Mitsubishi Outlander 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 168700,
    condition: "excellent",
    features: ["خليجي","Outlander","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فولكس واجن Tiguan 2020",
    titleEnglish: "Volkswagen Tiguan 2020",
    description: "فولكس واجن Tiguan 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Volkswagen Tiguan 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 164800,
    condition: "excellent",
    features: ["خليجي","Tiguan","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فولكس واجن Touareg 2020",
    titleEnglish: "Volkswagen Touareg 2020",
    description: "فولكس واجن Touareg 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Volkswagen Touareg 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 110100,
    condition: "new",
    features: ["خليجي","Touareg","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فولفو XC90 2020",
    titleEnglish: "Volvo XC90 2020",
    description: "فولفو XC90 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Volvo XC90 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 181200,
    condition: "new",
    features: ["خليجي","XC90","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فولفو XC60 2020",
    titleEnglish: "Volvo XC60 2020",
    description: "فولفو XC60 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Volvo XC60 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 215200,
    condition: "excellent",
    features: ["خليجي","XC60","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تسلا Model S 2020",
    titleEnglish: "Tesla Model S 2020",
    description: "تسلا Model S 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Tesla Model S 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كهربائية",
    price: 219100,
    condition: "excellent",
    features: ["خليجي","Model S","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تسلا Model 3 2020 — مستورد",
    titleEnglish: "Tesla Model 3 2020 — Imported",
    description: "تسلا Model 3 2020 مستورد، فحص شامل متوفر، جاهز للمعاينة يومياً في الإمارات.",
    descriptionEnglish: "Tesla Model 3 2020 imported specs, full inspection available, ready for viewing across the UAE.",
    subcategory: "كهربائية",
    price: 163100,
    condition: "used",
    features: ["مستورد","Model 3","فحص متوفر","صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إنفينيتي QX80 2020 — مستورد",
    titleEnglish: "Infiniti QX80 2020 — Imported",
    description: "إنفينيتي QX80 2020 مستورد، فحص شامل متوفر، جاهز للمعاينة يومياً في الإمارات.",
    descriptionEnglish: "Infiniti QX80 2020 imported specs, full inspection available, ready for viewing across the UAE.",
    subcategory: "سيارات عائلية",
    price: 249200,
    condition: "used",
    features: ["مستورد","QX80","فحص متوفر","صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إنفينيتي QX60 2020",
    titleEnglish: "Infiniti QX60 2020",
    description: "إنفينيتي QX60 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Infiniti QX60 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 193200,
    condition: "excellent",
    features: ["خليجي","QX60","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جينيسيس G70 2020",
    titleEnglish: "Genesis G70 2020",
    description: "جينيسيس G70 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Genesis G70 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 191900,
    condition: "excellent",
    features: ["خليجي","G70","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جينيسيس G80 2020",
    titleEnglish: "Genesis G80 2020",
    description: "جينيسيس G80 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Genesis G80 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 225900,
    condition: "excellent",
    features: ["خليجي","G80","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "سوزوكي Swift 2020",
    titleEnglish: "Suzuki Swift 2020",
    description: "سوزوكي Swift 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Suzuki Swift 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 153500,
    condition: "excellent",
    features: ["خليجي","Swift","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "سوزوكي Jimny 2020",
    titleEnglish: "Suzuki Jimny 2020",
    description: "سوزوكي Jimny 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Suzuki Jimny 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "أوف رود",
    price: 97500,
    condition: "new",
    features: ["خليجي","Jimny","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "سوبارو Outback 2020",
    titleEnglish: "Subaru Outback 2020",
    description: "سوبارو Outback 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Subaru Outback 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 100100,
    condition: "new",
    features: ["خليجي","Outback","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "سوبارو Forester 2020",
    titleEnglish: "Subaru Forester 2020",
    description: "سوبارو Forester 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Subaru Forester 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 135400,
    condition: "excellent",
    features: ["خليجي","Forester","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "دودج Charger 2020",
    titleEnglish: "Dodge Charger 2020",
    description: "دودج Charger 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Dodge Charger 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "رياضية",
    price: 169100,
    condition: "excellent",
    features: ["خليجي","Charger","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "دودج Challenger 2020",
    titleEnglish: "Dodge Challenger 2020",
    description: "دودج Challenger 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Dodge Challenger 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "رياضية",
    price: 207000,
    condition: "used",
    features: ["خليجي","Challenger","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جاكوار F-Pace 2020",
    titleEnglish: "Jaguar F-Pace 2020",
    description: "جاكوار F-Pace 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Jaguar F-Pace 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 241800,
    condition: "used",
    features: ["خليجي","F-Pace","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جاكوار E-Pace 2020",
    titleEnglish: "Jaguar E-Pace 2020",
    description: "جاكوار E-Pace 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Jaguar E-Pace 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 185800,
    condition: "excellent",
    features: ["خليجي","E-Pace","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بنتلي Bentayga 2020",
    titleEnglish: "Bentley Bentayga 2020",
    description: "بنتلي Bentayga 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Bentley Bentayga 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 678400,
    condition: "excellent",
    features: ["خليجي","Bentayga","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بنتلي Continental 2020 — مستورد",
    titleEnglish: "Bentley Continental 2020 — Imported",
    description: "بنتلي Continental 2020 مستورد، فحص شامل متوفر، جاهز للمعاينة يومياً في الإمارات.",
    descriptionEnglish: "Bentley Continental 2020 imported specs, full inspection available, ready for viewing across the UAE.",
    subcategory: "سيارات فاخرة",
    price: 716300,
    condition: "excellent",
    features: ["مستورد","Continental","فحص متوفر","صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "رولز رويس Cullinan 2020 — مستورد",
    titleEnglish: "Rolls-Royce Cullinan 2020 — Imported",
    description: "رولز رويس Cullinan 2020 مستورد، فحص شامل متوفر، جاهز للمعاينة يومياً في الإمارات.",
    descriptionEnglish: "Rolls-Royce Cullinan 2020 imported specs, full inspection available, ready for viewing across the UAE.",
    subcategory: "سيارات فاخرة",
    price: 712400,
    condition: "excellent",
    features: ["مستورد","Cullinan","فحص متوفر","صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "رولز رويس Ghost 2020",
    titleEnglish: "Rolls-Royce Ghost 2020",
    description: "رولز رويس Ghost 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Rolls-Royce Ghost 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 652500,
    condition: "new",
    features: ["خليجي","Ghost","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فيراري Roma 2020",
    titleEnglish: "Ferrari Roma 2020",
    description: "فيراري Roma 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Ferrari Roma 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "رياضية",
    price: 651200,
    condition: "new",
    features: ["خليجي","Roma","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فيراري SF90 2020",
    titleEnglish: "Ferrari SF90 2020",
    description: "فيراري SF90 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Ferrari SF90 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 685200,
    condition: "excellent",
    features: ["خليجي","SF90","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لامبورغيني Urus 2020",
    titleEnglish: "Lamborghini Urus 2020",
    description: "لامبورغيني Urus 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Lamborghini Urus 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 685200,
    condition: "excellent",
    features: ["خليجي","Urus","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لامبورغيني Huracán 2020",
    titleEnglish: "Lamborghini Huracán 2020",
    description: "لامبورغيني Huracán 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Lamborghini Huracán 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "رياضية",
    price: 723100,
    condition: "used",
    features: ["خليجي","Huracán","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مازيراتي Levante 2020",
    titleEnglish: "Maserati Levante 2020",
    description: "مازيراتي Levante 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Maserati Levante 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 723100,
    condition: "used",
    features: ["خليجي","Levante","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مازيراتي Ghibli 2020",
    titleEnglish: "Maserati Ghibli 2020",
    description: "مازيراتي Ghibli 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Maserati Ghibli 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات فاخرة",
    price: 665800,
    condition: "excellent",
    features: ["خليجي","Ghibli","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جيلي Coolray 2020",
    titleEnglish: "Geely Coolray 2020",
    description: "جيلي Coolray 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Geely Coolray 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 102100,
    condition: "excellent",
    features: ["خليجي","Coolray","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جيلي Monjaro 2020",
    titleEnglish: "Geely Monjaro 2020",
    description: "جيلي Monjaro 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Geely Monjaro 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 136100,
    condition: "excellent",
    features: ["خليجي","Monjaro","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إم جي MG5 2020",
    titleEnglish: "MG MG5 2020",
    description: "إم جي MG5 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "MG MG5 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيدان",
    price: 130900,
    condition: "excellent",
    features: ["خليجي","MG5","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إم جي MG6 2020",
    titleEnglish: "MG MG6 2020",
    description: "إم جي MG6 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "MG MG6 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كروس أوفر",
    price: 164900,
    condition: "new",
    features: ["خليجي","MG6","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي واي دي Han 2020",
    titleEnglish: "BYD Han 2020",
    description: "بي واي دي Han 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "BYD Han 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "كهربائية",
    price: 164900,
    condition: "new",
    features: ["خليجي","Han","جاهز للتسجيل","استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي واي دي Tang 2020 — مستورد",
    titleEnglish: "BYD Tang 2020 — Imported",
    description: "بي واي دي Tang 2020 مستورد، فحص شامل متوفر، جاهز للمعاينة يومياً في الإمارات.",
    descriptionEnglish: "BYD Tang 2020 imported specs, full inspection available, ready for viewing across the UAE.",
    subcategory: "كهربائية",
    price: 110200,
    condition: "excellent",
    features: ["مستورد","Tang","فحص متوفر","صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إيسوزو D-Max 2020 — مستورد",
    titleEnglish: "Isuzu D-Max 2020 — Imported",
    description: "إيسوزو D-Max 2020 مستورد، فحص شامل متوفر، جاهز للمعاينة يومياً في الإمارات.",
    descriptionEnglish: "Isuzu D-Max 2020 imported specs, full inspection available, ready for viewing across the UAE.",
    subcategory: "بيك أب",
    price: 111500,
    condition: "excellent",
    features: ["مستورد","D-Max","فحص متوفر","صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إيسوزو MU-X 2020",
    titleEnglish: "Isuzu MU-X 2020",
    description: "إيسوزو MU-X 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل.",
    descriptionEnglish: "Isuzu MU-X 2020 GCC specs, clear service history, no major accidents, ready to register.",
    subcategory: "سيارات عائلية",
    price: 144200,
    condition: "used",
    features: ["خليجي","MU-X","جاهز للتسجيل","استخدام شخصي"],
  },
];

export const LIVE_CARS_ALL_BRANDS_COUNT = LIVE_CARS_ALL_BRANDS.length;
