import type { LiveCarSeed } from "@/services/listings/live-cars-all-brands";

/** One professional UAE live ad for every CAR_BRAND_MODELS entry not already in the catalog. */
export const LIVE_CARS_REMAINING_MODELS: LiveCarSeed[] = [
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تويوتا Camry 2019 — مستورد",
    titleEnglish: "Toyota Camry 2019 — Imported",
    description: "تويوتا Camry 2019 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Toyota Camry 2019 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيدان",
    price: 49500,
    condition: "used",
    features: ["مستورد", "Camry", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تويوتا Corolla 2020 — فل أوبشن",
    titleEnglish: "Toyota Corolla 2020 — Full Option",
    description: "تويوتا Corolla 2020 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Toyota Corolla 2020 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 54700,
    condition: "used",
    features: ["خليجي", "Corolla", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تويوتا Hilux 2021",
    titleEnglish: "Toyota Hilux 2021",
    description: "تويوتا Hilux 2021 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Toyota Hilux 2021 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "بيك أب",
    price: 93900,
    condition: "excellent",
    features: ["خليجي", "Hilux", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تويوتا Yaris 2022",
    titleEnglish: "Toyota Yaris 2022",
    description: "تويوتا Yaris 2022 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Toyota Yaris 2022 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 65100,
    condition: "excellent",
    features: ["خليجي", "Yaris", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تويوتا Fortuner 2023 — فل أوبشن",
    titleEnglish: "Toyota Fortuner 2023 — Full Option",
    description: "تويوتا Fortuner 2023 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Toyota Fortuner 2023 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيارات عائلية",
    price: 98300,
    condition: "excellent",
    features: ["خليجي", "Fortuner", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تويوتا RAV4 2024 — مستورد",
    titleEnglish: "Toyota RAV4 2024 — Imported",
    description: "تويوتا RAV4 2024 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Toyota RAV4 2024 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "كروس أوفر",
    price: 103500,
    condition: "excellent",
    features: ["مستورد", "RAV4", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تويوتا Highlander 2025",
    titleEnglish: "Toyota Highlander 2025",
    description: "تويوتا Highlander 2025 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Toyota Highlander 2025 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات عائلية",
    price: 108700,
    condition: "new",
    features: ["خليجي", "Highlander", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تويوتا Avalon 2026 — فل أوبشن",
    titleEnglish: "Toyota Avalon 2026 — Full Option",
    description: "تويوتا Avalon 2026 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Toyota Avalon 2026 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 85900,
    condition: "new",
    features: ["خليجي", "Avalon", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تويوتا Supra 2019",
    titleEnglish: "Toyota Supra 2019",
    description: "تويوتا Supra 2019 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Toyota Supra 2019 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "رياضية",
    price: 146100,
    condition: "used",
    features: ["خليجي", "Supra", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "نيسان Sunny 2020",
    titleEnglish: "Nissan Sunny 2020",
    description: "نيسان Sunny 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Nissan Sunny 2020 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 60300,
    condition: "used",
    features: ["خليجي", "Sunny", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "نيسان X-Trail 2021 — مستورد",
    titleEnglish: "Nissan X-Trail 2021 — Imported",
    description: "نيسان X-Trail 2021 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Nissan X-Trail 2021 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "كروس أوفر",
    price: 93500,
    condition: "excellent",
    features: ["مستورد", "X-Trail", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "نيسان Kicks 2022",
    titleEnglish: "Nissan Kicks 2022",
    description: "نيسان Kicks 2022 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Nissan Kicks 2022 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 98700,
    condition: "excellent",
    features: ["خليجي", "Kicks", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "نيسان Pathfinder 2023",
    titleEnglish: "Nissan Pathfinder 2023",
    description: "نيسان Pathfinder 2023 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Nissan Pathfinder 2023 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات عائلية",
    price: 103900,
    condition: "excellent",
    features: ["خليجي", "Pathfinder", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "نيسان Maxima 2024 — فل أوبشن",
    titleEnglish: "Nissan Maxima 2024 — Full Option",
    description: "نيسان Maxima 2024 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Nissan Maxima 2024 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 72000,
    condition: "excellent",
    features: ["خليجي", "Maxima", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "نيسان Navara 2025",
    titleEnglish: "Nissan Navara 2025",
    description: "نيسان Navara 2025 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Nissan Navara 2025 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "بيك أب",
    price: 111200,
    condition: "new",
    features: ["خليجي", "Navara", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "نيسان GT-R 2026 — مستورد",
    titleEnglish: "Nissan GT-R 2026 — Imported",
    description: "نيسان GT-R 2026 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Nissan GT-R 2026 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "رياضية",
    price: 173400,
    condition: "new",
    features: ["مستورد", "GT-R", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هوندا CR-V 2019 — فل أوبشن",
    titleEnglish: "Honda CR-V 2019 — Full Option",
    description: "هوندا CR-V 2019 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Honda CR-V 2019 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "كروس أوفر",
    price: 79600,
    condition: "used",
    features: ["خليجي", "CR-V", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هوندا HR-V 2020",
    titleEnglish: "Honda HR-V 2020",
    description: "هوندا HR-V 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Honda HR-V 2020 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 84800,
    condition: "used",
    features: ["خليجي", "HR-V", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هوندا Pilot 2021",
    titleEnglish: "Honda Pilot 2021",
    description: "هوندا Pilot 2021 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Honda Pilot 2021 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات عائلية",
    price: 90000,
    condition: "excellent",
    features: ["خليجي", "Pilot", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هوندا City 2022 — فل أوبشن",
    titleEnglish: "Honda City 2022 — Full Option",
    description: "هوندا City 2022 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Honda City 2022 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 67200,
    condition: "excellent",
    features: ["خليجي", "City", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هوندا Odyssey 2023 — مستورد",
    titleEnglish: "Honda Odyssey 2023 — Imported",
    description: "هوندا Odyssey 2023 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Honda Odyssey 2023 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيارات عائلية",
    price: 100400,
    condition: "excellent",
    features: ["مستورد", "Odyssey", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس GX 2024",
    titleEnglish: "Lexus GX 2024",
    description: "لكزس GX 2024 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Lexus GX 2024 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات عائلية",
    price: 218600,
    condition: "excellent",
    features: ["خليجي", "GX", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس RX 2025 — فل أوبشن",
    titleEnglish: "Lexus RX 2025 — Full Option",
    description: "لكزس RX 2025 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Lexus RX 2025 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيارات فاخرة",
    price: 223800,
    condition: "new",
    features: ["خليجي", "RX", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس NX 2026",
    titleEnglish: "Lexus NX 2026",
    description: "لكزس NX 2026 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Lexus NX 2026 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات فاخرة",
    price: 229000,
    condition: "new",
    features: ["خليجي", "NX", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس ES 2019",
    titleEnglish: "Lexus ES 2019",
    description: "لكزس ES 2019 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Lexus ES 2019 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 198200,
    condition: "used",
    features: ["خليجي", "ES", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس IS 2020 — مستورد",
    titleEnglish: "Lexus IS 2020 — Imported",
    description: "لكزس IS 2020 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Lexus IS 2020 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيدان",
    price: 203400,
    condition: "used",
    features: ["مستورد", "IS", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس GS 2021",
    titleEnglish: "Lexus GS 2021",
    description: "لكزس GS 2021 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Lexus GS 2021 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 199500,
    condition: "excellent",
    features: ["خليجي", "GS", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس LS 2022",
    titleEnglish: "Lexus LS 2022",
    description: "لكزس LS 2022 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Lexus LS 2022 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 319700,
    condition: "excellent",
    features: ["خليجي", "LS", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس UX 2023 — فل أوبشن",
    titleEnglish: "Lexus UX 2023 — Full Option",
    description: "لكزس UX 2023 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Lexus UX 2023 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيارات فاخرة",
    price: 112900,
    condition: "excellent",
    features: ["خليجي", "UX", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس RC 2024",
    titleEnglish: "Lexus RC 2024",
    description: "لكزس RC 2024 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Lexus RC 2024 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "رياضية",
    price: 215100,
    condition: "excellent",
    features: ["خليجي", "RC", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لكزس LC 2025 — مستورد",
    titleEnglish: "Lexus LC 2025 — Imported",
    description: "لكزس LC 2025 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Lexus LC 2025 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "رياضية",
    price: 220300,
    condition: "new",
    features: ["مستورد", "LC", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مرسيدس C-Class 2026 — فل أوبشن",
    titleEnglish: "Mercedes-Benz C-Class 2026 — Full Option",
    description: "مرسيدس C-Class 2026 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Mercedes-Benz C-Class 2026 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 128500,
    condition: "new",
    features: ["خليجي", "C-Class", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مرسيدس E-Class 2019",
    titleEnglish: "Mercedes-Benz E-Class 2019",
    description: "مرسيدس E-Class 2019 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Mercedes-Benz E-Class 2019 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 97700,
    condition: "used",
    features: ["خليجي", "E-Class", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مرسيدس S-Class 2020",
    titleEnglish: "Mercedes-Benz S-Class 2020",
    description: "مرسيدس S-Class 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Mercedes-Benz S-Class 2020 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 314900,
    condition: "used",
    features: ["خليجي", "S-Class", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مرسيدس GLC 2021 — فل أوبشن",
    titleEnglish: "Mercedes-Benz GLC 2021 — Full Option",
    description: "مرسيدس GLC 2021 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Mercedes-Benz GLC 2021 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "رياضية",
    price: 205100,
    condition: "excellent",
    features: ["خليجي", "GLC", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مرسيدس GLE 2022 — مستورد",
    titleEnglish: "Mercedes-Benz GLE 2022 — Imported",
    description: "مرسيدس GLE 2022 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Mercedes-Benz GLE 2022 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيارات فاخرة",
    price: 210300,
    condition: "excellent",
    features: ["مستورد", "GLE", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مرسيدس GLS 2023",
    titleEnglish: "Mercedes-Benz GLS 2023",
    description: "مرسيدس GLS 2023 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Mercedes-Benz GLS 2023 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 330500,
    condition: "excellent",
    features: ["خليجي", "GLS", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مرسيدس A-Class 2024 — فل أوبشن",
    titleEnglish: "Mercedes-Benz A-Class 2024 — Full Option",
    description: "مرسيدس A-Class 2024 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Mercedes-Benz A-Class 2024 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 123700,
    condition: "excellent",
    features: ["خليجي", "A-Class", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مرسيدس CLA 2025",
    titleEnglish: "Mercedes-Benz CLA 2025",
    description: "مرسيدس CLA 2025 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Mercedes-Benz CLA 2025 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 128900,
    condition: "new",
    features: ["خليجي", "CLA", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مرسيدس Maybach 2026",
    titleEnglish: "Mercedes-Benz Maybach 2026",
    description: "مرسيدس Maybach 2026 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Mercedes-Benz Maybach 2026 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات فاخرة",
    price: 337000,
    condition: "new",
    features: ["خليجي", "Maybach", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو X3 2019 — مستورد",
    titleEnglish: "BMW X3 2019 — Imported",
    description: "بي إم دبليو X3 2019 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "BMW X3 2019 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيارات فاخرة",
    price: 191200,
    condition: "used",
    features: ["مستورد", "X3", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو X1 2020",
    titleEnglish: "BMW X1 2020",
    description: "بي إم دبليو X1 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "BMW X1 2020 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات فاخرة",
    price: 99400,
    condition: "used",
    features: ["خليجي", "X1", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو X6 2021",
    titleEnglish: "BMW X6 2021",
    description: "بي إم دبليو X6 2021 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "BMW X6 2021 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات فاخرة",
    price: 201600,
    condition: "excellent",
    features: ["خليجي", "X6", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو 3 Series 2022 — فل أوبشن",
    titleEnglish: "BMW 3 Series 2022 — Full Option",
    description: "بي إم دبليو 3 Series 2022 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "BMW 3 Series 2022 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 109800,
    condition: "excellent",
    features: ["خليجي", "3 Series", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو 5 Series 2023",
    titleEnglish: "BMW 5 Series 2023",
    description: "بي إم دبليو 5 Series 2023 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "BMW 5 Series 2023 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 212000,
    condition: "excellent",
    features: ["خليجي", "5 Series", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو 7 Series 2024 — مستورد",
    titleEnglish: "BMW 7 Series 2024 — Imported",
    description: "بي إم دبليو 7 Series 2024 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "BMW 7 Series 2024 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيدان",
    price: 332200,
    condition: "excellent",
    features: ["مستورد", "7 Series", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو M3 2025 — فل أوبشن",
    titleEnglish: "BMW M3 2025 — Full Option",
    description: "بي إم دبليو M3 2025 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "BMW M3 2025 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "رياضية",
    price: 222400,
    condition: "new",
    features: ["خليجي", "M3", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو M5 2026",
    titleEnglish: "BMW M5 2026",
    description: "بي إم دبليو M5 2026 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "BMW M5 2026 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "رياضية",
    price: 227600,
    condition: "new",
    features: ["خليجي", "M5", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو iX 2019",
    titleEnglish: "BMW iX 2019",
    description: "بي إم دبليو iX 2019 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "BMW iX 2019 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كهربائية",
    price: 196800,
    condition: "used",
    features: ["خليجي", "iX", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي إم دبليو i4 2020 — فل أوبشن",
    titleEnglish: "BMW i4 2020 — Full Option",
    description: "بي إم دبليو i4 2020 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "BMW i4 2020 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "كهربائية",
    price: 202000,
    condition: "used",
    features: ["خليجي", "i4", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "أودي A6 2021 — مستورد",
    titleEnglish: "Audi A6 2021 — Imported",
    description: "أودي A6 2021 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Audi A6 2021 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيدان",
    price: 207200,
    condition: "excellent",
    features: ["مستورد", "A6", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "أودي A8 2022",
    titleEnglish: "Audi A8 2022",
    description: "أودي A8 2022 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Audi A8 2022 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 327400,
    condition: "excellent",
    features: ["خليجي", "A8", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "أودي Q3 2023 — فل أوبشن",
    titleEnglish: "Audi Q3 2023 — Full Option",
    description: "أودي Q3 2023 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Audi Q3 2023 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيارات فاخرة",
    price: 111500,
    condition: "excellent",
    features: ["خليجي", "Q3", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "أودي Q5 2024",
    titleEnglish: "Audi Q5 2024",
    description: "أودي Q5 2024 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Audi Q5 2024 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات فاخرة",
    price: 213700,
    condition: "excellent",
    features: ["خليجي", "Q5", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "أودي Q7 2025",
    titleEnglish: "Audi Q7 2025",
    description: "أودي Q7 2025 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Audi Q7 2025 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات عائلية",
    price: 218900,
    condition: "new",
    features: ["خليجي", "Q7", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "أودي Q8 2026 — مستورد",
    titleEnglish: "Audi Q8 2026 — Imported",
    description: "أودي Q8 2026 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Audi Q8 2026 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيارات فاخرة",
    price: 224100,
    condition: "new",
    features: ["مستورد", "Q8", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "أودي e-tron 2019",
    titleEnglish: "Audi e-tron 2019",
    description: "أودي e-tron 2019 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Audi e-tron 2019 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كهربائية",
    price: 193300,
    condition: "used",
    features: ["خليجي", "e-tron", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "أودي RS6 2020",
    titleEnglish: "Audi RS6 2020",
    description: "أودي RS6 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Audi RS6 2020 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "رياضية",
    price: 198500,
    condition: "used",
    features: ["خليجي", "RS6", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بورش Panamera 2021 — فل أوبشن",
    titleEnglish: "Porsche Panamera 2021 — Full Option",
    description: "بورش Panamera 2021 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Porsche Panamera 2021 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 203700,
    condition: "excellent",
    features: ["خليجي", "Panamera", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بورش 911 2022",
    titleEnglish: "Porsche 911 2022",
    description: "بورش 911 2022 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Porsche 911 2022 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "رياضية",
    price: 323900,
    condition: "excellent",
    features: ["خليجي", "911", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بورش Taycan 2023 — مستورد",
    titleEnglish: "Porsche Taycan 2023 — Imported",
    description: "بورش Taycan 2023 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Porsche Taycan 2023 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "كهربائية",
    price: 214100,
    condition: "excellent",
    features: ["مستورد", "Taycan", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بورش Cayman 2024 — فل أوبشن",
    titleEnglish: "Porsche Cayman 2024 — Full Option",
    description: "بورش Cayman 2024 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Porsche Cayman 2024 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "رياضية",
    price: 219300,
    condition: "excellent",
    features: ["خليجي", "Cayman", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بورش Boxster 2025",
    titleEnglish: "Porsche Boxster 2025",
    description: "بورش Boxster 2025 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Porsche Boxster 2025 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "رياضية",
    price: 224500,
    condition: "new",
    features: ["خليجي", "Boxster", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لاند روفر Discovery Sport 2026",
    titleEnglish: "Land Rover Discovery Sport 2026",
    description: "لاند روفر Discovery Sport 2026 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Land Rover Discovery Sport 2026 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 229700,
    condition: "new",
    features: ["خليجي", "Discovery Sport", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لاند روفر Range Rover 2019 — فل أوبشن",
    titleEnglish: "Land Rover Range Rover 2019 — Full Option",
    description: "لاند روفر Range Rover 2019 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Land Rover Range Rover 2019 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيارات فاخرة",
    price: 198900,
    condition: "used",
    features: ["خليجي", "Range Rover", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "رنج روفر Range Rover Velar 2020 — مستورد",
    titleEnglish: "Range Rover Velar 2020 — Imported",
    description: "رنج روفر Range Rover Velar 2020 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Range Rover Velar 2020 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيارات فاخرة",
    price: 195000,
    condition: "used",
    features: ["مستورد", "Range Rover Velar", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "رنج روفر Range Rover Evoque 2021",
    titleEnglish: "Range Rover Evoque 2021",
    description: "رنج روفر Range Rover Evoque 2021 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Range Rover Evoque 2021 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات فاخرة",
    price: 200200,
    condition: "excellent",
    features: ["خليجي", "Range Rover Evoque", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جيب Cherokee 2022 — فل أوبشن",
    titleEnglish: "Jeep Cherokee 2022 — Full Option",
    description: "جيب Cherokee 2022 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Jeep Cherokee 2022 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "كروس أوفر",
    price: 92400,
    condition: "excellent",
    features: ["خليجي", "Cherokee", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جيب Compass 2023",
    titleEnglish: "Jeep Compass 2023",
    description: "جيب Compass 2023 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Jeep Compass 2023 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 97600,
    condition: "excellent",
    features: ["خليجي", "Compass", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جيب Gladiator 2024",
    titleEnglish: "Jeep Gladiator 2024",
    description: "جيب Gladiator 2024 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Jeep Gladiator 2024 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "بيك أب",
    price: 108800,
    condition: "excellent",
    features: ["خليجي", "Gladiator", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جيب Renegade 2025 — مستورد",
    titleEnglish: "Jeep Renegade 2025 — Imported",
    description: "جيب Renegade 2025 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Jeep Renegade 2025 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "كروس أوفر",
    price: 108000,
    condition: "new",
    features: ["مستورد", "Renegade", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فورد Explorer 2026",
    titleEnglish: "Ford Explorer 2026",
    description: "فورد Explorer 2026 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Ford Explorer 2026 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 113200,
    condition: "new",
    features: ["خليجي", "Explorer", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فورد Edge 2019",
    titleEnglish: "Ford Edge 2019",
    description: "فورد Edge 2019 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Ford Edge 2019 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 82400,
    condition: "used",
    features: ["خليجي", "Edge", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فورد Escape 2020 — فل أوبشن",
    titleEnglish: "Ford Escape 2020 — Full Option",
    description: "فورد Escape 2020 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Ford Escape 2020 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 59600,
    condition: "used",
    features: ["خليجي", "Escape", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فورد Ranger 2021",
    titleEnglish: "Ford Ranger 2021",
    description: "فورد Ranger 2021 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Ford Ranger 2021 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "بيك أب",
    price: 98800,
    condition: "excellent",
    features: ["خليجي", "Ranger", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فورد Bronco 2022 — مستورد",
    titleEnglish: "Ford Bronco 2022 — Imported",
    description: "فورد Bronco 2022 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Ford Bronco 2022 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "أوف رود",
    price: 98000,
    condition: "excellent",
    features: ["مستورد", "Bronco", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "شيفروليه Silverado 2023 — فل أوبشن",
    titleEnglish: "Chevrolet Silverado 2023 — Full Option",
    description: "شيفروليه Silverado 2023 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Chevrolet Silverado 2023 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "بيك أب",
    price: 109200,
    condition: "excellent",
    features: ["خليجي", "Silverado", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "شيفروليه Malibu 2024",
    titleEnglish: "Chevrolet Malibu 2024",
    description: "شيفروليه Malibu 2024 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Chevrolet Malibu 2024 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 80400,
    condition: "excellent",
    features: ["خليجي", "Malibu", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "شيفروليه Traverse 2025",
    titleEnglish: "Chevrolet Traverse 2025",
    description: "شيفروليه Traverse 2025 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Chevrolet Traverse 2025 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 104500,
    condition: "new",
    features: ["خليجي", "Traverse", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "شيفروليه Camaro 2026 — فل أوبشن",
    titleEnglish: "Chevrolet Camaro 2026 — Full Option",
    description: "شيفروليه Camaro 2026 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Chevrolet Camaro 2026 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "رياضية",
    price: 172700,
    condition: "new",
    features: ["خليجي", "Camaro", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جي إم سي Terrain 2019 — مستورد",
    titleEnglish: "GMC Terrain 2019 — Imported",
    description: "جي إم سي Terrain 2019 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "GMC Terrain 2019 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "كروس أوفر",
    price: 78900,
    condition: "used",
    features: ["مستورد", "Terrain", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جي إم سي Acadia 2020",
    titleEnglish: "GMC Acadia 2020",
    description: "جي إم سي Acadia 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "GMC Acadia 2020 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 84100,
    condition: "used",
    features: ["خليجي", "Acadia", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جي إم سي Canyon 2021 — فل أوبشن",
    titleEnglish: "GMC Canyon 2021 — Full Option",
    description: "جي إم سي Canyon 2021 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "GMC Canyon 2021 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "بيك أب",
    price: 95300,
    condition: "excellent",
    features: ["خليجي", "Canyon", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هيونداي Elantra 2022",
    titleEnglish: "Hyundai Elantra 2022",
    description: "هيونداي Elantra 2022 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Hyundai Elantra 2022 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 66500,
    condition: "excellent",
    features: ["خليجي", "Elantra", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هيونداي Sonata 2023",
    titleEnglish: "Hyundai Sonata 2023",
    description: "هيونداي Sonata 2023 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Hyundai Sonata 2023 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 71700,
    condition: "excellent",
    features: ["خليجي", "Sonata", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هيونداي Palisade 2024 — مستورد",
    titleEnglish: "Hyundai Palisade 2024 — Imported",
    description: "هيونداي Palisade 2024 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Hyundai Palisade 2024 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيدان",
    price: 76900,
    condition: "excellent",
    features: ["مستورد", "Palisade", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هيونداي Creta 2025",
    titleEnglish: "Hyundai Creta 2025",
    description: "هيونداي Creta 2025 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Hyundai Creta 2025 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 110100,
    condition: "new",
    features: ["خليجي", "Creta", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "هيونداي Accent 2026",
    titleEnglish: "Hyundai Accent 2026",
    description: "هيونداي Accent 2026 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Hyundai Accent 2026 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 87300,
    condition: "new",
    features: ["خليجي", "Accent", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "كيا K5 2019 — فل أوبشن",
    titleEnglish: "Kia K5 2019 — Full Option",
    description: "كيا K5 2019 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Kia K5 2019 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 56500,
    condition: "used",
    features: ["خليجي", "K5", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "كيا Cerato 2020",
    titleEnglish: "Kia Cerato 2020",
    description: "كيا Cerato 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Kia Cerato 2020 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 61700,
    condition: "used",
    features: ["خليجي", "Cerato", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "كيا Telluride 2021 — مستورد",
    titleEnglish: "Kia Telluride 2021 — Imported",
    description: "كيا Telluride 2021 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Kia Telluride 2021 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيارات عائلية",
    price: 94900,
    condition: "excellent",
    features: ["مستورد", "Telluride", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "كيا Carnival 2022 — فل أوبشن",
    titleEnglish: "Kia Carnival 2022 — Full Option",
    description: "كيا Carnival 2022 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Kia Carnival 2022 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيارات عائلية",
    price: 91000,
    condition: "excellent",
    features: ["خليجي", "Carnival", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "كيا Seltos 2023",
    titleEnglish: "Kia Seltos 2023",
    description: "كيا Seltos 2023 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Kia Seltos 2023 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 96200,
    condition: "excellent",
    features: ["خليجي", "Seltos", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مازدا CX-30 2024",
    titleEnglish: "Mazda CX-30 2024",
    description: "مازدا CX-30 2024 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Mazda CX-30 2024 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 101400,
    condition: "excellent",
    features: ["خليجي", "CX-30", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مازدا Mazda3 2025 — فل أوبشن",
    titleEnglish: "Mazda3 2025 — Full Option",
    description: "مازدا Mazda3 2025 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Mazda3 2025 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 78600,
    condition: "new",
    features: ["خليجي", "Mazda3", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مازدا Mazda6 2026 — مستورد",
    titleEnglish: "Mazda6 2026 — Imported",
    description: "مازدا Mazda6 2026 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Mazda6 2026 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيدان",
    price: 83800,
    condition: "new",
    features: ["مستورد", "Mazda6", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مازدا MX-5 2019",
    titleEnglish: "Mazda MX-5 2019",
    description: "مازدا MX-5 2019 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Mazda MX-5 2019 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "رياضية",
    price: 144000,
    condition: "used",
    features: ["خليجي", "MX-5", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "ميتسوبيشي Lancer 2020 — فل أوبشن",
    titleEnglish: "Mitsubishi Lancer 2020 — Full Option",
    description: "ميتسوبيشي Lancer 2020 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Mitsubishi Lancer 2020 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 58200,
    condition: "used",
    features: ["خليجي", "Lancer", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "ميتسوبيشي ASX 2021",
    titleEnglish: "Mitsubishi ASX 2021",
    description: "ميتسوبيشي ASX 2021 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Mitsubishi ASX 2021 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 91400,
    condition: "excellent",
    features: ["خليجي", "ASX", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "ميتسوبيشي Montero 2022",
    titleEnglish: "Mitsubishi Montero 2022",
    description: "ميتسوبيشي Montero 2022 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Mitsubishi Montero 2022 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "أوف رود",
    price: 96600,
    condition: "excellent",
    features: ["خليجي", "Montero", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "ميتسوبيشي L200 2023 — مستورد",
    titleEnglish: "Mitsubishi L200 2023 — Imported",
    description: "ميتسوبيشي L200 2023 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Mitsubishi L200 2023 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "بيك أب",
    price: 107800,
    condition: "excellent",
    features: ["مستورد", "L200", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فولكس واجن Golf 2024",
    titleEnglish: "Volkswagen Golf 2024",
    description: "فولكس واجن Golf 2024 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Volkswagen Golf 2024 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 79000,
    condition: "excellent",
    features: ["خليجي", "Golf", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فولكس واجن Passat 2025",
    titleEnglish: "Volkswagen Passat 2025",
    description: "فولكس واجن Passat 2025 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Volkswagen Passat 2025 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 84200,
    condition: "new",
    features: ["خليجي", "Passat", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فولكس واجن Teramont 2026 — فل أوبشن",
    titleEnglish: "Volkswagen Teramont 2026 — Full Option",
    description: "فولكس واجن Teramont 2026 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Volkswagen Teramont 2026 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "بيك أب",
    price: 123400,
    condition: "new",
    features: ["خليجي", "Teramont", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فولكس واجن ID.4 2019",
    titleEnglish: "Volkswagen ID.4 2019",
    description: "فولكس واجن ID.4 2019 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Volkswagen ID.4 2019 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كهربائية",
    price: 77500,
    condition: "used",
    features: ["خليجي", "ID.4", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فولفو XC40 2020 — مستورد",
    titleEnglish: "Volvo XC40 2020 — Imported",
    description: "فولفو XC40 2020 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Volvo XC40 2020 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "كروس أوفر",
    price: 165700,
    condition: "used",
    features: ["مستورد", "XC40", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فولفو S90 2021 — فل أوبشن",
    titleEnglish: "Volvo S90 2021 — Full Option",
    description: "فولفو S90 2021 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Volvo S90 2021 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 170900,
    condition: "excellent",
    features: ["خليجي", "S90", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فولفو S60 2022",
    titleEnglish: "Volvo S60 2022",
    description: "فولفو S60 2022 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Volvo S60 2022 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 176100,
    condition: "excellent",
    features: ["خليجي", "S60", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تسلا Model X 2023",
    titleEnglish: "Tesla Model X 2023",
    description: "تسلا Model X 2023 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Tesla Model X 2023 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كهربائية",
    price: 181300,
    condition: "excellent",
    features: ["خليجي", "Model X", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "تسلا Cybertruck 2024 — فل أوبشن",
    titleEnglish: "Tesla Cybertruck 2024 — Full Option",
    description: "تسلا Cybertruck 2024 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Tesla Cybertruck 2024 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "كهربائية",
    price: 306500,
    condition: "excellent",
    features: ["خليجي", "Cybertruck", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إنفينيتي QX55 2025 — مستورد",
    titleEnglish: "Infiniti QX55 2025 — Imported",
    description: "إنفينيتي QX55 2025 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Infiniti QX55 2025 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "كروس أوفر",
    price: 191700,
    condition: "new",
    features: ["مستورد", "QX55", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إنفينيتي Q50 2026",
    titleEnglish: "Infiniti Q50 2026",
    description: "إنفينيتي Q50 2026 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Infiniti Q50 2026 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 196900,
    condition: "new",
    features: ["خليجي", "Q50", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إنفينيتي Q60 2019 — فل أوبشن",
    titleEnglish: "Infiniti Q60 2019 — Full Option",
    description: "إنفينيتي Q60 2019 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Infiniti Q60 2019 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 166100,
    condition: "used",
    features: ["خليجي", "Q60", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جينيسيس G90 2020",
    titleEnglish: "Genesis G90 2020",
    description: "جينيسيس G90 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Genesis G90 2020 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 171300,
    condition: "used",
    features: ["خليجي", "G90", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جينيسيس GV70 2021",
    titleEnglish: "Genesis GV70 2021",
    description: "جينيسيس GV70 2021 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Genesis GV70 2021 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 176500,
    condition: "excellent",
    features: ["خليجي", "GV70", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جينيسيس GV80 2022 — مستورد",
    titleEnglish: "Genesis GV80 2022 — Imported",
    description: "جينيسيس GV80 2022 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Genesis GV80 2022 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "كروس أوفر",
    price: 181700,
    condition: "excellent",
    features: ["مستورد", "GV80", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "سوزوكي Vitara 2023",
    titleEnglish: "Suzuki Vitara 2023",
    description: "سوزوكي Vitara 2023 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Suzuki Vitara 2023 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 103900,
    condition: "excellent",
    features: ["خليجي", "Vitara", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "سوزوكي Ertiga 2024",
    titleEnglish: "Suzuki Ertiga 2024",
    description: "سوزوكي Ertiga 2024 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Suzuki Ertiga 2024 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 100000,
    condition: "excellent",
    features: ["خليجي", "Ertiga", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "سوزوكي Ciaz 2025 — فل أوبشن",
    titleEnglish: "Suzuki Ciaz 2025 — Full Option",
    description: "سوزوكي Ciaz 2025 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Suzuki Ciaz 2025 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 77200,
    condition: "new",
    features: ["خليجي", "Ciaz", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "سوبارو XV 2026",
    titleEnglish: "Subaru XV 2026",
    description: "سوبارو XV 2026 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Subaru XV 2026 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 110400,
    condition: "new",
    features: ["خليجي", "XV", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "سوبارو Impreza 2019 — مستورد",
    titleEnglish: "Subaru Impreza 2019 — Imported",
    description: "سوبارو Impreza 2019 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Subaru Impreza 2019 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "كروس أوفر",
    price: 79600,
    condition: "used",
    features: ["مستورد", "Impreza", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "سوبارو WRX 2020 — فل أوبشن",
    titleEnglish: "Subaru WRX 2020 — Full Option",
    description: "سوبارو WRX 2020 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Subaru WRX 2020 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "رياضية",
    price: 147800,
    condition: "used",
    features: ["خليجي", "WRX", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "دودج Durango 2021",
    titleEnglish: "Dodge Durango 2021",
    description: "دودج Durango 2021 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Dodge Durango 2021 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 90000,
    condition: "excellent",
    features: ["خليجي", "Durango", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "دودج Ram 2022",
    titleEnglish: "Dodge Ram 2022",
    description: "دودج Ram 2022 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Dodge Ram 2022 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "بيك أب",
    price: 101200,
    condition: "excellent",
    features: ["خليجي", "Ram", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جاكوار XF 2023 — فل أوبشن",
    titleEnglish: "Jaguar XF 2023 — Full Option",
    description: "جاكوار XF 2023 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Jaguar XF 2023 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 213400,
    condition: "excellent",
    features: ["خليجي", "XF", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جاكوار XE 2024 — مستورد",
    titleEnglish: "Jaguar XE 2024 — Imported",
    description: "جاكوار XE 2024 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Jaguar XE 2024 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيدان",
    price: 218600,
    condition: "excellent",
    features: ["مستورد", "XE", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جاكوار F-Type 2025",
    titleEnglish: "Jaguar F-Type 2025",
    description: "جاكوار F-Type 2025 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Jaguar F-Type 2025 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "رياضية",
    price: 223800,
    condition: "new",
    features: ["خليجي", "F-Type", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بنتلي Flying Spur 2026 — فل أوبشن",
    titleEnglish: "Bentley Flying Spur 2026 — Full Option",
    description: "بنتلي Flying Spur 2026 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Bentley Flying Spur 2026 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيدان",
    price: 754000,
    condition: "new",
    features: ["خليجي", "Flying Spur", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "رولز رويس Phantom 2019",
    titleEnglish: "Rolls-Royce Phantom 2019",
    description: "رولز رويس Phantom 2019 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Rolls-Royce Phantom 2019 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كهربائية",
    price: 893200,
    condition: "used",
    features: ["خليجي", "Phantom", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "رولز رويس Wraith 2020",
    titleEnglish: "Rolls-Royce Wraith 2020",
    description: "رولز رويس Wraith 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Rolls-Royce Wraith 2020 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 728400,
    condition: "used",
    features: ["خليجي", "Wraith", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فيراري 488 2021 — مستورد",
    titleEnglish: "Ferrari 488 2021 — Imported",
    description: "فيراري 488 2021 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Ferrari 488 2021 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "رياضية",
    price: 684500,
    condition: "excellent",
    features: ["مستورد", "488", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فيراري F8 2022",
    titleEnglish: "Ferrari F8 2022",
    description: "فيراري F8 2022 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Ferrari F8 2022 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "رياضية",
    price: 689700,
    condition: "excellent",
    features: ["خليجي", "F8", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "فيراري Purosangue 2023",
    titleEnglish: "Ferrari Purosangue 2023",
    description: "فيراري Purosangue 2023 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Ferrari Purosangue 2023 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات فاخرة",
    price: 904900,
    condition: "excellent",
    features: ["خليجي", "Purosangue", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لامبورغيني Aventador 2024 — فل أوبشن",
    titleEnglish: "Lamborghini Aventador 2024 — Full Option",
    description: "لامبورغيني Aventador 2024 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Lamborghini Aventador 2024 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "رياضية",
    price: 910100,
    condition: "excellent",
    features: ["خليجي", "Aventador", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "لامبورغيني Revuelto 2025",
    titleEnglish: "Lamborghini Revuelto 2025",
    description: "لامبورغيني Revuelto 2025 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Lamborghini Revuelto 2025 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "رياضية",
    price: 915300,
    condition: "new",
    features: ["خليجي", "Revuelto", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مازيراتي Quattroporte 2026 — مستورد",
    titleEnglish: "Maserati Quattroporte 2026 — Imported",
    description: "مازيراتي Quattroporte 2026 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "Maserati Quattroporte 2026 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "سيدان",
    price: 225500,
    condition: "new",
    features: ["مستورد", "Quattroporte", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "مازيراتي Grecale 2019 — فل أوبشن",
    titleEnglish: "Maserati Grecale 2019 — Full Option",
    description: "مازيراتي Grecale 2019 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "Maserati Grecale 2019 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "سيارات فاخرة",
    price: 194700,
    condition: "used",
    features: ["خليجي", "Grecale", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جيلي Okavango 2020",
    titleEnglish: "Geely Okavango 2020",
    description: "جيلي Okavango 2020 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Geely Okavango 2020 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيارات عائلية",
    price: 66900,
    condition: "used",
    features: ["خليجي", "Okavango", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "جيلي Emgrand 2021",
    titleEnglish: "Geely Emgrand 2021",
    description: "جيلي Emgrand 2021 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "Geely Emgrand 2021 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "سيدان",
    price: 72100,
    condition: "excellent",
    features: ["خليجي", "Emgrand", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إم جي ZS 2022 — فل أوبشن",
    titleEnglish: "MG ZS 2022 — Full Option",
    description: "إم جي ZS 2022 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "MG ZS 2022 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "كروس أوفر",
    price: 77300,
    condition: "excellent",
    features: ["خليجي", "ZS", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إم جي HS 2023 — مستورد",
    titleEnglish: "MG HS 2023 — Imported",
    description: "إم جي HS 2023 مستورد، فحص شامل متوفر عند المعاينة، جاهز للتسجيل بعد الإجراءات الرسمية.",
    descriptionEnglish: "MG HS 2023 imported specs, full inspection available on viewing, ready to register after official procedures.",
    subcategory: "كروس أوفر",
    price: 82500,
    condition: "excellent",
    features: ["مستورد", "HS", "فحص متوفر", "صيانة دورية"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "إم جي RX5 2024",
    titleEnglish: "MG RX5 2024",
    description: "إم جي RX5 2024 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "MG RX5 2024 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كروس أوفر",
    price: 87700,
    condition: "excellent",
    features: ["خليجي", "RX5", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي واي دي Seal 2025 — فل أوبشن",
    titleEnglish: "BYD Seal 2025 — Full Option",
    description: "بي واي دي Seal 2025 فل أوبشن مواصفات خليجية، صيانة وكالة، استخدام شخصي، بدون حوادث جوهرية.",
    descriptionEnglish: "BYD Seal 2025 full option GCC specs, agency service history, personal use, no major accidents.",
    subcategory: "كهربائية",
    price: 92900,
    condition: "new",
    features: ["خليجي", "Seal", "فل أوبشن", "صيانة وكالة"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي واي دي Atto 3 2026",
    titleEnglish: "BYD Atto 3 2026",
    description: "بي واي دي Atto 3 2026 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "BYD Atto 3 2026 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كهربائية",
    price: 89000,
    condition: "new",
    features: ["خليجي", "Atto 3", "جاهز للتسجيل", "استخدام شخصي"],
  },
  {
    categoryId: "cars",
    imageCategory: "cars",
    title: "بي واي دي Song 2019",
    titleEnglish: "BYD Song 2019",
    description: "بي واي دي Song 2019 مواصفات خليجية، صيانة واضحة، بدون حوادث جوهرية، جاهز للتسجيل والمعاينة في الإمارات.",
    descriptionEnglish: "BYD Song 2019 GCC specs, clear service history, no major accidents, ready to register and view in the UAE.",
    subcategory: "كهربائية",
    price: 58200,
    condition: "used",
    features: ["خليجي", "Song", "جاهز للتسجيل", "استخدام شخصي"],
  },
];

export const LIVE_CARS_REMAINING_COUNT = LIVE_CARS_REMAINING_MODELS.length;
