import type { Listing, ListingCondition, ListingImageTone } from "@/types";
import type { CategorySpecs } from "@/types/domain/category-fields";
import {
  galleryFromPool,
  type ImageFallbackCategory,
} from "@/shared/constants/image-fallbacks";
import {
  SHOWCASE_SELLER_ID,
  SHOWCASE_SOURCE,
} from "@/shared/listings/showcase-listing";

const DEMO_FOOTER_AR =
  "هذا إعلان تجريبي من معرض سوقنا لتوضيح تجربة المنصة، وليس إعلاناً من بائع مستقل.";
const DEMO_FOOTER_EN =
  "This is a Sooqna showcase listing to demonstrate the marketplace. It is not an ad from an independent seller.";

const SHOWCASE_SELLER: Listing["seller"] = {
  id: SHOWCASE_SELLER_ID,
  name: "سوقنا — معرض تجريبي",
  nameEnglish: "Sooqna Showcase",
  sellerType: "individual",
  isVerified: false,
  joinedAt: "2026-09-01T00:00:00.000Z",
};

const TONES: ListingImageTone[] = ["gold", "amber", "sky", "slate", "rose"];

type ShowcaseSeed = {
  key: string;
  categoryId: string;
  subcategory: string;
  title: string;
  titleEnglish: string;
  description: string;
  descriptionEnglish: string;
  price: number;
  emirate: string;
  city: string;
  area: string;
  condition: ListingCondition;
  categorySpecs?: CategorySpecs;
  carSpecs?: Listing["carSpecs"];
  realEstateSpecs?: Listing["realEstateSpecs"];
  electronicsSpecs?: Listing["electronicsSpecs"];
  features?: string[];
  deliveryOption?: Listing["deliveryOption"];
  mediaCategory?: ImageFallbackCategory;
};

function mediaFor(categoryId: string, slug: string): { imageUrl: string; images: string[] } {
  const key = (categoryId in {
    cars: 1,
    "real-estate": 1,
    electronics: 1,
    mobiles: 1,
    furniture: 1,
    jobs: 1,
    fashion: 1,
    services: 1,
    pets: 1,
    kids: 1,
    books: 1,
    sports: 1,
    food: 1,
  }
    ? categoryId
    : "default") as ImageFallbackCategory;
  const images = galleryFromPool(key, slug, 4);
  return { imageUrl: images[0] ?? "", images };
}

function withDemoCopy(arabic: string, english: string): { description: string; descriptionEnglish: string } {
  return {
    description: `${arabic}\n\n${DEMO_FOOTER_AR}`,
    descriptionEnglish: `${english}\n\n${DEMO_FOOTER_EN}`,
  };
}

function buildListing(seed: ShowcaseSeed, index: number): Listing {
  const slug = `showcase-${seed.key}`;
  const media = mediaFor(seed.mediaCategory ?? seed.categoryId, slug);
  const copy = withDemoCopy(seed.description, seed.descriptionEnglish);
  const postedAt = new Date(Date.UTC(2026, 8, 8, 12, 0, 0) - index * 6 * 60 * 60 * 1000).toISOString();

  return {
    id: `showcase-${seed.categoryId}-${String(index + 1).padStart(2, "0")}`,
    slug,
    title: seed.title,
    titleEnglish: seed.titleEnglish,
    description: copy.description,
    descriptionEnglish: copy.descriptionEnglish,
    categoryId: seed.categoryId,
    subcategory: seed.subcategory,
    city: seed.city,
    emirate: seed.emirate,
    area: seed.area,
    country: "الإمارات العربية المتحدة",
    price: seed.price,
    currency: "AED",
    condition: seed.condition,
    status: "active",
    isFeatured: false,
    isPremium: false,
    views: 0,
    imageUrl: media.imageUrl,
    images: media.images,
    seller: { ...SHOWCASE_SELLER },
    imageTone: TONES[index % TONES.length],
    isDemo: true,
    source: SHOWCASE_SOURCE,
    escrowAvailable: false,
    verifiedSeller: false,
    postedAt,
    contactMethod: "chat",
    deliveryOption: seed.deliveryOption ?? "both",
    negotiable: false,
    categorySpecs: seed.categorySpecs,
    carSpecs: seed.carSpecs,
    realEstateSpecs: seed.realEstateSpecs,
    electronicsSpecs: seed.electronicsSpecs,
    features: seed.features,
  };
}

const SEEDS: ShowcaseSeed[] = [
  {
    key: "toyota-land-cruiser-2022",
    categoryId: "cars",
    subcategory: "سيارات مستعملة",
    title: "تويوتا لاند كروزر 2022 — معرض تجريبي",
    titleEnglish: "Toyota Land Cruiser 2022 — showcase",
    description:
      "نموذج تويوتا لاند كروزر لتوضيح صفحة السيارات: مواصفات خليجية، عداد منطقي، وصور توضيحية من معرض سوقنا.",
    descriptionEnglish:
      "A Toyota Land Cruiser showcase example with Gulf specs and illustrative marketplace photography.",
    price: 268000,
    emirate: "دبي",
    city: "دبي",
    area: "البرشاء",
    condition: "used",
    deliveryOption: "pickup",
    features: ["دفع رباعي", "كاميرا", "مقاعد جلد", "ملاحة", "Apple CarPlay"],
    categorySpecs: {
      brand: "Toyota",
      model: "Land Cruiser",
      condition: "used",
      year: "2022",
      emirate: "دبي",
      city: "البرشاء",
      mileage: "42000",
      transmission: "أوتوماتيك",
      fuelType: "بنزين",
      engineSize: "4.0",
      regionalSpecs: "خليجي",
      exteriorColor: "أبيض",
      interiorColor: "بيج",
      warranty: "نعم",
      accidentHistory: "بدون حوادث",
      serviceHistory: "وكالة كاملة",
    },
    carSpecs: {
      mileage: "42,000 كم",
      transmission: "أوتوماتيك",
      fuel: "بنزين",
      warranty: "ساري",
      accidentHistory: "بدون حوادث",
      regionalSpecs: "خليجي",
      serviceHistory: "وكالة كاملة",
      vinAvailable: false,
    },
  },
  {
    key: "mercedes-s-class-showcase",
    categoryId: "cars",
    subcategory: "سيارات فاخرة",
    title: "مرسيدس S-Class — معرض تجريبي",
    titleEnglish: "Mercedes-Benz S-Class — showcase",
    description:
      "نموذج سيارة فاخرة لتوضيح قسم السيارات الفاخرة في سوقنا. الصور توضيحية من المعرض التجريبي.",
    descriptionEnglish:
      "A luxury sedan showcase for the premium cars subcategory. Photos are illustrative.",
    price: 395000,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "جزيرة الريم",
    condition: "used",
    deliveryOption: "pickup",
    features: ["مقاعد جلد", "فتحة سقف", "ملاحة", "كاميرا", "مثبت سرعة"],
    categorySpecs: {
      brand: "Mercedes-Benz",
      model: "S-Class",
      condition: "used",
      year: "2021",
      emirate: "أبوظبي",
      city: "جزيرة الريم",
      mileage: "28000",
      transmission: "أوتوماتيك",
      fuelType: "بنزين",
      engineSize: "3.0",
      regionalSpecs: "خليجي",
      exteriorColor: "أسود",
      interiorColor: "بني",
      warranty: "نعم",
      accidentHistory: "بدون حوادث",
      serviceHistory: "وكالة كاملة",
    },
    carSpecs: {
      mileage: "28,000 كم",
      transmission: "أوتوماتيك",
      fuel: "بنزين",
      warranty: "ساري",
      accidentHistory: "بدون حوادث",
      regionalSpecs: "خليجي",
      serviceHistory: "وكالة كاملة",
      vinAvailable: false,
    },
  },
  {
    key: "tesla-model-y-showcase",
    categoryId: "cars",
    subcategory: "سيارات كهربائية",
    title: "تسلا Model Y — معرض تجريبي",
    titleEnglish: "Tesla Model Y — showcase",
    description:
      "نموذج سيارة كهربائية لتوضيح فلاتر الوقود والكهرباء في قسم السيارات.",
    descriptionEnglish:
      "An electric vehicle showcase for the EV subcategory and fuel-type filters.",
    price: 165000,
    emirate: "دبي",
    city: "دبي",
    area: "الخليج التجاري",
    condition: "used",
    deliveryOption: "pickup",
    features: ["كاميرا", "ملاحة", "Apple CarPlay", "بلوتوث"],
    categorySpecs: {
      brand: "Tesla",
      model: "Model Y",
      condition: "used",
      year: "2023",
      emirate: "دبي",
      city: "الخليج التجاري",
      mileage: "18000",
      transmission: "أوتوماتيك",
      fuelType: "كهربائي",
      engineSize: "Dual Motor",
      regionalSpecs: "أمريكي",
      exteriorColor: "أبيض",
      interiorColor: "أسود",
      warranty: "نعم",
      accidentHistory: "بدون حوادث",
      serviceHistory: "صيانة دورية",
    },
    carSpecs: {
      mileage: "18,000 كم",
      transmission: "أوتوماتيك",
      fuel: "كهربائي",
      warranty: "ساري",
      accidentHistory: "بدون حوادث",
      regionalSpecs: "أمريكي",
      serviceHistory: "صيانة دورية",
      vinAvailable: false,
    },
  },
  {
    key: "toyota-oem-filters-showcase",
    categoryId: "cars",
    subcategory: "قطع غيار",
    title: "فلاتر تويوتا أصلية — معرض تجريبي",
    titleEnglish: "Toyota OEM filters — showcase",
    description:
      "نموذج قطع غيار لتوضيح قسم الإكسسوارات دون انتحال محل تجاري حقيقي.",
    descriptionEnglish:
      "An auto-parts showcase for the spare-parts subcategory. Not a real shop listing.",
    price: 180,
    emirate: "الشارقة",
    city: "الشارقة",
    area: "الصناعية",
    condition: "new",
    deliveryOption: "both",
    categorySpecs: {
      brand: "Toyota",
      model: "Land Cruiser",
      condition: "new",
      year: "2022",
      emirate: "الشارقة",
      city: "الصناعية",
      mileage: "0",
      transmission: "أوتوماتيك",
      fuelType: "بنزين",
      engineSize: "—",
      regionalSpecs: "خليجي",
      exteriorColor: "أخرى",
      exteriorColorOther: "لا ينطبق",
      interiorColor: "أخرى",
      interiorColorOther: "لا ينطبق",
      warranty: "نعم",
      accidentHistory: "بدون حوادث",
      serviceHistory: "غير متوفر",
    },
  },
  {
    key: "apartment-sale-marina",
    categoryId: "real-estate",
    subcategory: "شقق للبيع",
    title: "شقة غرفتين للبيع — دبي مارينا (تجريبي)",
    titleEnglish: "2BR apartment for sale — Dubai Marina (demo)",
    description:
      "نموذج شقة للبيع لتوضيح بطاقات العقارات: الغرف، المساحة، والموقع. ليس عقاراً معروضاً من مطور أو مالك حقيقي.",
    descriptionEnglish:
      "A sale-apartment showcase for real-estate cards. Not an offer from a real owner or developer.",
    price: 1850000,
    emirate: "دبي",
    city: "دبي",
    area: "دبي مارينا",
    condition: "used",
    deliveryOption: "not_applicable",
    categorySpecs: {
      propertyType: "شقة",
      purpose: "للبيع",
      bedrooms: 2,
      bathrooms: 2,
      area: 1180,
      floor: "12",
      parking: 1,
      furnished: "شبه مفروش",
      completionStatus: "جاهز",
      developer: "أخرى",
      community: "دبي مارينا",
      titleDeedReady: "نعم",
      emirate: "دبي",
      city: "دبي مارينا",
    },
    realEstateSpecs: {
      bedrooms: 2,
      bathrooms: 2,
      parking: 1,
      areaSqft: 1180,
      furnished: "شبه مفروش",
      developer: "—",
      community: "دبي مارينا",
      amenities: ["مسبح", "جيم", "أمن 24 ساعة"],
    },
  },
  {
    key: "apartment-rent-khalifa-city",
    categoryId: "real-estate",
    subcategory: "شقق للإيجار",
    title: "شقة للإيجار — مدينة خليفة (تجريبي)",
    titleEnglish: "Apartment for rent — Khalifa City (demo)",
    description:
      "نموذج إيجار سكني لتوضيح الغرض «للإيجار» في فلاتر العقارات.",
    descriptionEnglish:
      "A rental-apartment showcase for the for-rent subcategory.",
    price: 72000,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "مدينة خليفة",
    condition: "used",
    deliveryOption: "not_applicable",
    categorySpecs: {
      propertyType: "شقة",
      purpose: "للإيجار",
      bedrooms: 1,
      bathrooms: 1,
      area: 780,
      floor: "5",
      parking: 1,
      furnished: "مفروش",
      completionStatus: "جاهز",
      developer: "أخرى",
      community: "مدينة خليفة",
      titleDeedReady: "نعم",
      emirate: "أبوظبي",
      city: "مدينة خليفة",
    },
    realEstateSpecs: {
      bedrooms: 1,
      bathrooms: 1,
      parking: 1,
      areaSqft: 780,
      furnished: "مفروش",
      developer: "—",
      community: "مدينة خليفة",
      amenities: ["موقف", "حراسة"],
    },
  },
  {
    key: "villa-yas-island",
    categoryId: "real-estate",
    subcategory: "فلل",
    title: "فيلا مستقلة — جزيرة ياس (تجريبي)",
    titleEnglish: "Detached villa — Yas Island (demo)",
    description:
      "نموذج فيلا لتوضيح معرض العقارات الفاخرة مع صور فيلات توضيحية مرخّصة للاستخدام.",
    descriptionEnglish:
      "A villa showcase with category-matched illustrative photography.",
    price: 6200000,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "جزيرة ياس",
    condition: "used",
    deliveryOption: "not_applicable",
    categorySpecs: {
      propertyType: "فيلا",
      purpose: "للبيع",
      bedrooms: 5,
      bathrooms: 6,
      area: 5200,
      floor: "أرضي + أول",
      parking: 3,
      furnished: "غير مفروش",
      completionStatus: "جاهز",
      developer: "أخرى",
      community: "جزيرة ياس",
      titleDeedReady: "نعم",
      emirate: "أبوظبي",
      city: "جزيرة ياس",
    },
    realEstateSpecs: {
      bedrooms: 5,
      bathrooms: 6,
      parking: 3,
      areaSqft: 5200,
      furnished: "غير مفروش",
      developer: "—",
      community: "جزيرة ياس",
      amenities: ["حديقة", "موقف خاص", "مطبخ مجهز"],
    },
  },
  {
    key: "office-business-bay-showcase",
    categoryId: "real-estate",
    subcategory: "مكاتب",
    title: "مكتب تجاري — الخليج التجاري (تجريبي)",
    titleEnglish: "Commercial office — Business Bay (demo)",
    description:
      "نموذج مكتب لتوضيح قسم المكاتب. المعرّف والرابط مختلفان عن سجل الاختبار القديم office-business-bay.",
    descriptionEnglish:
      "An office showcase. Id and slug do not match the retired QA fixture office-business-bay.",
    price: 145000,
    emirate: "دبي",
    city: "دبي",
    area: "الخليج التجاري",
    condition: "used",
    deliveryOption: "not_applicable",
    categorySpecs: {
      propertyType: "مكتب",
      purpose: "للإيجار",
      bedrooms: 0,
      bathrooms: 2,
      area: 980,
      floor: "18",
      parking: 2,
      furnished: "شبه مفروش",
      completionStatus: "جاهز",
      developer: "أخرى",
      community: "الخليج التجاري",
      titleDeedReady: "نعم",
      emirate: "دبي",
      city: "الخليج التجاري",
    },
    realEstateSpecs: {
      bedrooms: 0,
      bathrooms: 2,
      parking: 2,
      areaSqft: 980,
      furnished: "شبه مفروش",
      developer: "—",
      community: "الخليج التجاري",
      amenities: ["استقبال", "مواقف"],
    },
  },
  {
    key: "macbook-pro-14-showcase",
    categoryId: "electronics",
    subcategory: "لابتوبات",
    title: "MacBook Pro 14 — معرض تجريبي",
    titleEnglish: "MacBook Pro 14 — showcase",
    description:
      "نموذج لابتوب لتوضيح قسم الإلكترونيات مع مواصفات تخزين ولون متوافقة.",
    descriptionEnglish:
      "A laptop showcase with matching storage and accessory attributes.",
    price: 6200,
    emirate: "دبي",
    city: "دبي",
    area: "ديرة",
    condition: "used",
    categorySpecs: {
      brand: "Apple",
      model: "MacBook Pro",
      condition: "used",
      warranty: "نعم",
      accessories: "شاحن أصلي وصندوق",
    },
    electronicsSpecs: {
      storage: "512 GB",
      color: "Space Gray",
      warranty: "ساري",
      accessories: "شاحن أصلي",
      purchaseDate: "2024-11-01",
    },
  },
  {
    key: "playstation-5-showcase",
    categoryId: "electronics",
    subcategory: "ألعاب",
    title: "PlayStation 5 — معرض تجريبي",
    titleEnglish: "PlayStation 5 — showcase",
    description: "نموذج جهاز ألعاب لتوضيح قسم الألعاب في الإلكترونيات.",
    descriptionEnglish: "A games-console showcase for the electronics category.",
    price: 1650,
    emirate: "الشارقة",
    city: "الشارقة",
    area: "النهدة",
    condition: "used",
    categorySpecs: {
      brand: "Sony",
      model: "PlayStation 5",
      condition: "used",
      warranty: "لا",
      accessories: "يد تحكم واحدة وكابل HDMI",
    },
    electronicsSpecs: {
      storage: "825 GB",
      color: "أبيض",
      warranty: "منتهي",
      accessories: "يد تحكم",
      purchaseDate: "2023-06-01",
    },
  },
  {
    key: "mirrorless-camera-showcase",
    categoryId: "electronics",
    subcategory: "كاميرات",
    title: "كاميرا بدون مرآة — معرض تجريبي",
    titleEnglish: "Mirrorless camera — showcase",
    description: "نموذج كاميرا لتوضيح قسم التصوير مع صور كاميرات توضيحية.",
    descriptionEnglish: "A camera showcase with category-matched photography.",
    price: 3400,
    emirate: "دبي",
    city: "دبي",
    area: "بر دبي",
    condition: "used",
    categorySpecs: {
      brand: "Sony",
      model: "أخرى",
      condition: "used",
      warranty: "نعم",
      accessories: "عدسة قياسية وحقيبة",
    },
    electronicsSpecs: {
      storage: "بطاقة 128 GB",
      color: "أسود",
      warranty: "ساري",
      accessories: "عدسة وحقيبة",
      purchaseDate: "2024-02-01",
    },
  },
  {
    key: "wireless-headphones-showcase",
    categoryId: "electronics",
    subcategory: "سماعات",
    title: "سماعات لاسلكية — معرض تجريبي",
    titleEnglish: "Wireless headphones — showcase",
    description: "نموذج سماعات لتغطية قسم السماعات في الإلكترونيات.",
    descriptionEnglish: "A headphones showcase for the audio subcategory.",
    price: 420,
    emirate: "عجمان",
    city: "عجمان",
    area: "الرميلة",
    condition: "new",
    categorySpecs: {
      brand: "Sony",
      model: "أخرى",
      condition: "new",
      warranty: "نعم",
      accessories: "علبة الشحن والكابل",
    },
    electronicsSpecs: {
      storage: "—",
      color: "أسود",
      warranty: "ساري",
      accessories: "علبة شحن",
      purchaseDate: "2026-08-01",
    },
  },
  {
    key: "iphone-16-pro-showcase",
    categoryId: "mobiles",
    subcategory: "آيفون",
    title: "iPhone 16 Pro 256GB — معرض تجريبي",
    titleEnglish: "iPhone 16 Pro 256GB — showcase",
    description:
      "نموذج آيفون بمواصفات متوافقة (التخزين، اللون، صحة البطارية) وصور هواتف توضيحية.",
    descriptionEnglish:
      "An iPhone showcase with matching storage, color, and battery fields.",
    price: 4299,
    emirate: "دبي",
    city: "دبي",
    area: "مركز دبي",
    condition: "new",
    categorySpecs: {
      brand: "Apple",
      model: "iPhone 16 Pro",
      storage: "256 GB",
      ram: "8 GB",
      color: "تيتانيوم",
      batteryHealth: "100%",
      warranty: "نعم",
      purchaseDate: "2026-08-15",
      accessoriesIncluded: "علبة وكابل USB-C",
      condition: "new",
    },
    electronicsSpecs: {
      storage: "256 GB",
      color: "تيتانيوم",
      warranty: "ساري",
      accessories: "علبة وكابل",
      purchaseDate: "2026-08-15",
    },
  },
  {
    key: "samsung-s24-ultra-showcase",
    categoryId: "mobiles",
    subcategory: "سامسونج",
    title: "Galaxy S24 Ultra — معرض تجريبي",
    titleEnglish: "Galaxy S24 Ultra — showcase",
    description: "نموذج سامسونج لتغطية قسم أندرويد في الموبايلات.",
    descriptionEnglish: "A Samsung phone showcase for the Android subcategory.",
    price: 2899,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "الكورنيش",
    condition: "used",
    categorySpecs: {
      brand: "Samsung",
      model: "Galaxy S24 Ultra",
      storage: "256 GB",
      ram: "12 GB",
      color: "أسود",
      batteryHealth: "94%",
      warranty: "نعم",
      purchaseDate: "2025-03-01",
      accessoriesIncluded: "شاحن وكفر",
      condition: "used",
    },
    electronicsSpecs: {
      storage: "256 GB",
      color: "أسود",
      warranty: "ساري",
      accessories: "شاحن وكفر",
      purchaseDate: "2025-03-01",
    },
  },
  {
    key: "ipad-pro-showcase",
    categoryId: "mobiles",
    subcategory: "أجهزة لوحية",
    title: "iPad Pro — معرض تجريبي",
    titleEnglish: "iPad Pro — showcase",
    description: "نموذج جهاز لوحي لتغطية قسم التابلت.",
    descriptionEnglish: "A tablet showcase for the tablets subcategory.",
    price: 3199,
    emirate: "دبي",
    city: "دبي",
    area: "المارينا",
    condition: "used",
    categorySpecs: {
      brand: "Apple",
      model: "iPad Pro",
      storage: "256 GB",
      ram: "8 GB",
      color: "رمادي",
      batteryHealth: "97%",
      warranty: "نعم",
      purchaseDate: "2025-09-01",
      accessoriesIncluded: "قلم ولوحة مفاتيح اختيارية غير مرفقة",
      condition: "used",
    },
    electronicsSpecs: {
      storage: "256 GB",
      color: "رمادي",
      warranty: "ساري",
      accessories: "بدون قلم",
      purchaseDate: "2025-09-01",
    },
  },
  {
    key: "phone-case-charger-showcase",
    categoryId: "mobiles",
    subcategory: "إكسسوارات",
    title: "كفر وشاحن آيفون — معرض تجريبي",
    titleEnglish: "iPhone case and charger — showcase",
    description: "نموذج إكسسوارات موبايل بأسعار توضيحية.",
    descriptionEnglish: "A phone-accessories showcase with illustrative pricing.",
    price: 95,
    emirate: "الشارقة",
    city: "الشارقة",
    area: "المجاز",
    condition: "new",
    categorySpecs: {
      brand: "Apple",
      model: "iPhone 16 Pro",
      storage: "64 GB",
      ram: "4 GB",
      color: "شفاف",
      batteryHealth: "لا ينطبق",
      warranty: "نعم",
      purchaseDate: "2026-08-01",
      accessoriesIncluded: "كفر وشاحن",
      condition: "new",
    },
  },
  {
    key: "bedroom-set-showcase",
    categoryId: "furniture",
    subcategory: "غرف نوم",
    title: "غرفة نوم خشبية — معرض تجريبي",
    titleEnglish: "Wooden bedroom set — showcase",
    description: "نموذج غرفة نوم لتوضيح قسم الأثاث مع صور غرف نوم توضيحية.",
    descriptionEnglish: "A bedroom-set showcase with matching furniture photography.",
    price: 2800,
    emirate: "دبي",
    city: "دبي",
    area: "القوز",
    condition: "used",
    categorySpecs: {
      furnitureType: "غرف نوم",
      condition: "used",
      material: "خشب",
      city: "القوز",
    },
  },
  {
    key: "modern-sofa-showcase",
    categoryId: "furniture",
    subcategory: "كنب",
    title: "كنب مودرن ثلاثي — معرض تجريبي",
    titleEnglish: "Modern 3-seater sofa — showcase",
    description: "نموذج كنب لتغطية قسم الأثاث المعيشي.",
    descriptionEnglish: "A sofa showcase for the living-room subcategory.",
    price: 1450,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "الخالدية",
    condition: "used",
    categorySpecs: {
      furnitureType: "كنب",
      condition: "used",
      material: "قماش",
      city: "الخالدية",
    },
  },
  {
    key: "dining-table-showcase",
    categoryId: "furniture",
    subcategory: "طاولات طعام",
    title: "طاولة طعام 6 كراسي — معرض تجريبي",
    titleEnglish: "6-seat dining table — showcase",
    description: "نموذج طاولة طعام لتغطية هذا التصنيف الفرعي.",
    descriptionEnglish: "A dining-table showcase.",
    price: 980,
    emirate: "الشارقة",
    city: "الشارقة",
    area: "الخان",
    condition: "used",
    categorySpecs: {
      furnitureType: "طاولات طعام",
      condition: "used",
      material: "خشب",
      city: "الخان",
    },
  },
  {
    key: "outdoor-furniture-showcase",
    categoryId: "furniture",
    subcategory: "أثاث خارجي",
    title: "طقم حديقة — معرض تجريبي",
    titleEnglish: "Garden furniture set — showcase",
    description: "نموذج أثاث خارجي لتغطية الشرفات والحدائق.",
    descriptionEnglish: "An outdoor-furniture showcase.",
    price: 760,
    emirate: "رأس الخيمة",
    city: "رأس الخيمة",
    area: "النخيل",
    condition: "used",
    categorySpecs: {
      furnitureType: "أثاث خارجي",
      condition: "used",
      material: "راتان",
      city: "النخيل",
    },
  },
  {
    key: "sales-executive-vacancy",
    categoryId: "jobs",
    subcategory: "مبيعات",
    title: "شاغر مبيعات — معرض تجريبي",
    titleEnglish: "Sales vacancy — showcase",
    description:
      "نموذج شاغر وظيفي من حساب سوقنا التجريبي. الشركة المذكورة هي حساب المعرض وليست شركة خارجية.",
    descriptionEnglish:
      "A job-vacancy showcase posted by the Sooqna showcase account, not an external employer.",
    price: 6500,
    emirate: "دبي",
    city: "دبي",
    area: "وسط المدينة",
    condition: "new",
    deliveryOption: "not_applicable",
    categorySpecs: {
      listingType: "vacancy",
      company: "سوقنا — معرض تجريبي",
      position: "موظف مبيعات",
      salary: "5,500 – 7,500",
      experience: "سنتان",
      employmentType: "دوام كامل",
      location: "دبي",
      gender: "أي",
    },
  },
  {
    key: "property-consultant-vacancy",
    categoryId: "jobs",
    subcategory: "عقارات",
    title: "مستشار عقاري — معرض تجريبي",
    titleEnglish: "Property consultant — showcase",
    description: "نموذج وظيفة عقارية لتغطية تصنيف الوظائف العقارية.",
    descriptionEnglish: "A real-estate jobs showcase vacancy.",
    price: 8000,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "المصفح",
    condition: "new",
    deliveryOption: "not_applicable",
    categorySpecs: {
      listingType: "vacancy",
      company: "سوقنا — معرض تجريبي",
      position: "مستشار عقاري",
      salary: "عمولة + أساسي",
      experience: "3 سنوات",
      employmentType: "دوام كامل",
      location: "أبوظبي",
      gender: "أي",
    },
  },
  {
    key: "delivery-rider-vacancy",
    categoryId: "jobs",
    subcategory: "توصيل",
    title: "سائق توصيل — معرض تجريبي",
    titleEnglish: "Delivery rider — showcase",
    description: "نموذج وظيفة توصيل لتغطية هذا التصنيف الفرعي.",
    descriptionEnglish: "A delivery-jobs showcase vacancy.",
    price: 3500,
    emirate: "الشارقة",
    city: "الشارقة",
    area: "المجاز",
    condition: "new",
    deliveryOption: "not_applicable",
    categorySpecs: {
      listingType: "vacancy",
      company: "سوقنا — معرض تجريبي",
      position: "سائق توصيل",
      salary: "3,000 – 4,000",
      experience: "رخصة سارية",
      employmentType: "دوام كامل",
      location: "الشارقة",
      gender: "أي",
    },
  },
  {
    key: "accountant-vacancy",
    categoryId: "jobs",
    subcategory: "محاسبة",
    title: "محاسب — معرض تجريبي",
    titleEnglish: "Accountant — showcase",
    description: "نموذج وظيفة محاسبة لتغطية هذا التصنيف.",
    descriptionEnglish: "An accounting-jobs showcase vacancy.",
    price: 9000,
    emirate: "دبي",
    city: "دبي",
    area: "الخليج التجاري",
    condition: "new",
    deliveryOption: "not_applicable",
    categorySpecs: {
      listingType: "vacancy",
      company: "سوقنا — معرض تجريبي",
      position: "محاسب",
      salary: "8,000 – 10,000",
      experience: "4 سنوات",
      employmentType: "دوام كامل",
      location: "دبي",
      gender: "أي",
    },
  },
  {
    key: "designer-seeker-showcase",
    categoryId: "jobs",
    subcategory: "تصميم",
    title: "مصمم يبحث عن عمل — معرض تجريبي",
    titleEnglish: "Designer seeking work — showcase",
    description:
      "نموذج باحث عن عمل لتوضيح نوع إعلان الوظائف الثاني دون بيانات شخصية حقيقية.",
    descriptionEnglish:
      "A job-seeker showcase. No real private contact details.",
    price: 7000,
    emirate: "دبي",
    city: "دبي",
    area: "مدينة دبي للإعلام",
    condition: "new",
    deliveryOption: "not_applicable",
    categorySpecs: {
      listingType: "seeker",
      position: "مصمم جرافيك",
      salary: "6,000 – 8,000",
      experience: "3 سنوات",
      availability: "فوري",
      location: "دبي / عن بُعد",
    },
  },
  {
    key: "wristwatch-showcase",
    categoryId: "fashion",
    subcategory: "ساعات",
    title: "ساعة كلاسيكية — معرض تجريبي",
    titleEnglish: "Classic wristwatch — showcase",
    description:
      "نموذج ساعة لتوضيح قسم الأزياء. ليست ساعة علامة تجارية مزيفة ولا إعلان تاجر ساعات حقيقي.",
    descriptionEnglish:
      "A watch showcase. Not a counterfeit branded listing and not a real dealer ad.",
    price: 1250,
    emirate: "دبي",
    city: "دبي",
    area: "ديرة",
    condition: "used",
  },
  {
    key: "leather-bag-showcase",
    categoryId: "fashion",
    subcategory: "حقائب",
    title: "حقيبة جلد — معرض تجريبي",
    titleEnglish: "Leather bag — showcase",
    description: "نموذج حقيبة لتغطية تصنيف الحقائب.",
    descriptionEnglish: "A handbags showcase listing.",
    price: 380,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "المارينا مول",
    condition: "used",
  },
  {
    key: "casual-outfit-showcase",
    categoryId: "fashion",
    subcategory: "ملابس",
    title: "طقم كاجوال — معرض تجريبي",
    titleEnglish: "Casual outfit — showcase",
    description: "نموذج ملابس لتغطية هذا التصنيف الفرعي.",
    descriptionEnglish: "A clothing showcase listing.",
    price: 160,
    emirate: "الشارقة",
    city: "الشارقة",
    area: "البحيرة",
    condition: "used",
  },
  {
    key: "oud-gift-set-showcase",
    categoryId: "fashion",
    subcategory: "عطور",
    title: "طقم عود — معرض تجريبي",
    titleEnglish: "Oud gift set — showcase",
    description: "نموذج عطور لتغطية قسم العطور دون انتحال علامة تجارية.",
    descriptionEnglish: "A fragrance showcase without impersonating a perfume house.",
    price: 220,
    emirate: "دبي",
    city: "دبي",
    area: "نايف",
    condition: "new",
  },
  {
    key: "home-cleaning-showcase",
    categoryId: "services",
    subcategory: "تنظيف",
    title: "تنظيف منزلي — معرض تجريبي",
    titleEnglish: "Home cleaning — showcase",
    description:
      "نموذج خدمة تنظيف باسم حساب سوقنا التجريبي وليس باسم شركة تنظيف خارجية.",
    descriptionEnglish:
      "A cleaning-service showcase under the Sooqna showcase account, not an external company.",
    price: 180,
    emirate: "دبي",
    city: "دبي",
    area: "جميرا",
    condition: "new",
    deliveryOption: "not_applicable",
    categorySpecs: {
      businessName: "سوقنا — معرض تجريبي",
      serviceCategory: "تنظيف",
      coverageArea: "دبي",
      availability: "حسب الموعد",
      experience: "معرض توضيحي",
    },
  },
  {
    key: "home-maintenance-showcase",
    categoryId: "services",
    subcategory: "صيانة",
    title: "صيانة منزلية — معرض تجريبي",
    titleEnglish: "Home maintenance — showcase",
    description: "نموذج صيانة لتغطية هذا التصنيف الفرعي.",
    descriptionEnglish: "A maintenance-service showcase.",
    price: 250,
    emirate: "الشارقة",
    city: "الشارقة",
    area: "المجاز",
    condition: "new",
    deliveryOption: "not_applicable",
    categorySpecs: {
      businessName: "سوقنا — معرض تجريبي",
      serviceCategory: "صيانة",
      coverageArea: "الشارقة",
      availability: "خلال 24 ساعة",
      experience: "معرض توضيحي",
    },
  },
  {
    key: "moving-service-showcase",
    categoryId: "services",
    subcategory: "نقل",
    title: "خدمة نقل عفش — معرض تجريبي",
    titleEnglish: "Moving service — showcase",
    description: "نموذج نقل عفش لتغطية قسم النقل.",
    descriptionEnglish: "A moving-service showcase.",
    price: 650,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "مدينة محمد بن زايد",
    condition: "new",
    deliveryOption: "not_applicable",
    categorySpecs: {
      businessName: "سوقنا — معرض تجريبي",
      serviceCategory: "نقل",
      coverageArea: "أبوظبي ودبي",
      availability: "حسب الموعد",
      experience: "معرض توضيحي",
    },
  },
  {
    key: "ac-service-showcase",
    categoryId: "services",
    subcategory: "تكييف",
    title: "صيانة تكييف — معرض تجريبي",
    titleEnglish: "AC servicing — showcase",
    description: "نموذج تكييف لتغطية هذا التصنيف.",
    descriptionEnglish: "An air-conditioning service showcase.",
    price: 220,
    emirate: "عجمان",
    city: "عجمان",
    area: "الراشدية",
    condition: "new",
    deliveryOption: "not_applicable",
    categorySpecs: {
      businessName: "سوقنا — معرض تجريبي",
      serviceCategory: "تكييف",
      coverageArea: "عجمان والشارقة",
      availability: "فوري",
      experience: "معرض توضيحي",
    },
  },
  {
    key: "cat-supplies-showcase",
    categoryId: "pets",
    subcategory: "قطط",
    title: "مستلزمات قطط — معرض تجريبي",
    titleEnglish: "Cat supplies — showcase",
    description:
      "نموذج مستلزمات قطط. ليس إعلان تبنّي أو بيع حيوان أليف حقيقي.",
    descriptionEnglish:
      "A cat-supplies showcase. Not a real pet sale or adoption listing.",
    price: 85,
    emirate: "دبي",
    city: "دبي",
    area: "الممزر",
    condition: "new",
  },
  {
    key: "dog-supplies-showcase",
    categoryId: "pets",
    subcategory: "كلاب",
    title: "مستلزمات كلاب — معرض تجريبي",
    titleEnglish: "Dog supplies — showcase",
    description: "نموذج مستلزمات كلاب لتغطية هذا التصنيف دون بيع حيوانات.",
    descriptionEnglish: "A dog-supplies showcase, not a live-animal listing.",
    price: 95,
    emirate: "الشارقة",
    city: "الشارقة",
    area: "الخان",
    condition: "new",
  },
  {
    key: "bird-cage-showcase",
    categoryId: "pets",
    subcategory: "طيور",
    title: "قفص طيور — معرض تجريبي",
    titleEnglish: "Bird cage — showcase",
    description: "نموذج مستلزمات طيور.",
    descriptionEnglish: "A bird-supplies showcase.",
    price: 140,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "مدينة زايد",
    condition: "new",
  },
  {
    key: "pet-accessories-showcase",
    categoryId: "pets",
    subcategory: "مستلزمات",
    title: "مستلزمات أليفة عامة — معرض تجريبي",
    titleEnglish: "General pet accessories — showcase",
    description: "نموذج مستلزمات عامة للحيوانات الأليفة.",
    descriptionEnglish: "A general pet-accessories showcase.",
    price: 55,
    emirate: "عجمان",
    city: "عجمان",
    area: "النعيمية",
    condition: "new",
  },
  {
    key: "stroller-showcase",
    categoryId: "kids",
    subcategory: "عربات أطفال",
    title: "عربة أطفال — معرض تجريبي",
    titleEnglish: "Baby stroller — showcase",
    description: "نموذج عربة أطفال لتوضيح قسم الأطفال.",
    descriptionEnglish: "A stroller showcase for the kids category.",
    price: 650,
    emirate: "دبي",
    city: "دبي",
    area: "المرابع العربية",
    condition: "used",
  },
  {
    key: "kids-toys-showcase",
    categoryId: "kids",
    subcategory: "ألعاب",
    title: "مجموعة ألعاب — معرض تجريبي",
    titleEnglish: "Toy set — showcase",
    description: "نموذج ألعاب أطفال.",
    descriptionEnglish: "A kids-toys showcase.",
    price: 120,
    emirate: "الشارقة",
    city: "الشارقة",
    area: "الناصرية",
    condition: "used",
  },
  {
    key: "kids-clothes-showcase",
    categoryId: "kids",
    subcategory: "ملابس أطفال",
    title: "ملابس أطفال — معرض تجريبي",
    titleEnglish: "Kids clothing — showcase",
    description: "نموذج ملابس أطفال.",
    descriptionEnglish: "A kids-clothing showcase.",
    price: 90,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "الشامخة",
    condition: "used",
  },
  {
    key: "kids-essentials-showcase",
    categoryId: "kids",
    subcategory: "مستلزمات",
    title: "مستلزمات أطفال — معرض تجريبي",
    titleEnglish: "Baby essentials — showcase",
    description: "نموذج مستلزمات أطفال عامة.",
    descriptionEnglish: "A baby-essentials showcase.",
    price: 75,
    emirate: "الفجيرة",
    city: "الفجيرة",
    area: "المدينة",
    condition: "new",
  },
  {
    key: "arabic-novels-showcase",
    categoryId: "books",
    subcategory: "كتب عربية",
    title: "مجموعة روايات عربية — معرض تجريبي",
    titleEnglish: "Arabic novels set — showcase",
    description: "نموذج كتب عربية لتوضيح قسم الكتب.",
    descriptionEnglish: "An Arabic-books showcase.",
    price: 80,
    emirate: "الشارقة",
    city: "الشارقة",
    area: "القصباء",
    condition: "used",
  },
  {
    key: "university-books-showcase",
    categoryId: "books",
    subcategory: "كتب جامعية",
    title: "كتب جامعية — معرض تجريبي",
    titleEnglish: "University textbooks — showcase",
    description: "نموذج كتب جامعية.",
    descriptionEnglish: "A university-textbooks showcase.",
    price: 150,
    emirate: "دبي",
    city: "دبي",
    area: "الأكاديمية",
    condition: "used",
  },
  {
    key: "fiction-paperbacks-showcase",
    categoryId: "books",
    subcategory: "روايات",
    title: "روايات ورقية — معرض تجريبي",
    titleEnglish: "Paperback novels — showcase",
    description: "نموذج روايات لتغطية هذا التصنيف.",
    descriptionEnglish: "A fiction-paperbacks showcase.",
    price: 45,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "جزيرة السعديات",
    condition: "used",
  },
  {
    key: "school-curriculum-showcase",
    categoryId: "books",
    subcategory: "مناهج",
    title: "كتب مناهج — معرض تجريبي",
    titleEnglish: "Curriculum books — showcase",
    description: "نموذج مناهج دراسية.",
    descriptionEnglish: "A school-curriculum showcase.",
    price: 110,
    emirate: "عجمان",
    city: "عجمان",
    area: "المويهات",
    condition: "used",
  },
  {
    key: "home-gym-showcase",
    categoryId: "sports",
    subcategory: "معدات رياضية",
    title: "أوزان منزلية — معرض تجريبي",
    titleEnglish: "Home weights — showcase",
    description: "نموذج معدات رياضية.",
    descriptionEnglish: "A home-gym equipment showcase.",
    price: 420,
    emirate: "دبي",
    city: "دبي",
    area: "البرشاء",
    condition: "used",
  },
  {
    key: "city-bike-showcase",
    categoryId: "sports",
    subcategory: "دراجات",
    title: "دراجة هوائية — معرض تجريبي",
    titleEnglish: "City bicycle — showcase",
    description: "نموذج دراجة لتغطية قسم الدراجات.",
    descriptionEnglish: "A bicycle showcase.",
    price: 890,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "جزيرة ياس",
    condition: "used",
  },
  {
    key: "yoga-fitness-showcase",
    categoryId: "sports",
    subcategory: "لياقة",
    title: "مستلزمات لياقة — معرض تجريبي",
    titleEnglish: "Fitness accessories — showcase",
    description: "نموذج لياقة منزلية.",
    descriptionEnglish: "A fitness-accessories showcase.",
    price: 130,
    emirate: "دبي",
    city: "دبي",
    area: "جميرا بيتش ريزيدنس",
    condition: "new",
  },
  {
    key: "camping-kit-showcase",
    categoryId: "sports",
    subcategory: "تخييم",
    title: "طقم تخييم — معرض تجريبي",
    titleEnglish: "Camping kit — showcase",
    description: "نموذج تخييم لتغطية هذا التصنيف.",
    descriptionEnglish: "A camping-gear showcase.",
    price: 340,
    emirate: "رأس الخيمة",
    city: "رأس الخيمة",
    area: "جبل جيس",
    condition: "used",
  },
  {
    key: "home-cooking-showcase",
    categoryId: "food",
    subcategory: "أكلات منزلية",
    title: "وجبات منزلية — معرض تجريبي",
    titleEnglish: "Home-cooked meals — showcase",
    description:
      "نموذج طعام منزلي بأسعار توضيحية للتجزئة. ليس مطبخاً تجارياً مرخّصاً باسم طرف ثالث.",
    descriptionEnglish:
      "A home-cooking showcase at retail pricing. Not a third-party licensed kitchen.",
    price: 45,
    emirate: "دبي",
    city: "دبي",
    area: "القوز",
    condition: "new",
    categorySpecs: {
      saleType: "retail",
      unitPrice: "AED 45 / وجبة",
      cuisine: "إماراتي",
      portion: "وجبة لشخصين",
      delivery: "كلاهما",
      freshness: "محضّر عند الطلب",
      city: "القوز",
    },
  },
  {
    key: "fujairah-dates-showcase",
    categoryId: "food",
    subcategory: "تمور",
    title: "تمر فاخر — معرض تجريبي",
    titleEnglish: "Premium dates — showcase",
    description: "نموذج تمور بأسعار توضيحية. ليس منتج مزرعة باسم تاجر محدد.",
    descriptionEnglish: "A dates showcase. Not a named farm or trader product.",
    price: 85,
    emirate: "الفجيرة",
    city: "الفجيرة",
    area: "البدية",
    condition: "new",
    categorySpecs: {
      saleType: "retail",
      unitPrice: "AED 85 / كرتون",
      cuisine: "إماراتي",
      portion: "كرتون 1 كجم",
      delivery: "توصيل متاح",
      freshness: "معلّب",
      city: "البدية",
    },
  },
  {
    key: "arabic-sweets-showcase",
    categoryId: "food",
    subcategory: "حلويات",
    title: "حلويات عربية — معرض تجريبي",
    titleEnglish: "Arabic sweets — showcase",
    description: "نموذج حلويات لتغطية هذا التصنيف.",
    descriptionEnglish: "An Arabic-sweets showcase.",
    price: 60,
    emirate: "الشارقة",
    city: "الشارقة",
    area: "القصباء",
    condition: "new",
    categorySpecs: {
      saleType: "retail",
      unitPrice: "AED 60 / علبة",
      cuisine: "حلويات",
      portion: "علبة ضيافة",
      delivery: "استلام فقط",
      freshness: "طازج يومياً",
      city: "القصباء",
    },
  },
  {
    key: "hospitality-tray-showcase",
    categoryId: "food",
    subcategory: "ضيافة",
    title: "صينية ضيافة — معرض تجريبي",
    titleEnglish: "Hospitality tray — showcase",
    description: "نموذج ضيافة لتغطية هذا التصنيف الفرعي.",
    descriptionEnglish: "A hospitality-tray showcase.",
    price: 120,
    emirate: "أبوظبي",
    city: "أبوظبي",
    area: "الكورنيش",
    condition: "new",
    categorySpecs: {
      saleType: "wholesale",
      unitPrice: "AED 120 / صينية",
      cuisine: "عربي",
      portion: "صينية لـ 8 أشخاص",
      delivery: "كلاهما",
      freshness: "محضّر عند الطلب",
      city: "الكورنيش",
    },
  },
];

export function getShowcaseCatalogListings(): Listing[] {
  return SEEDS.map((seed, index) => buildListing(seed, index));
}

export function genericShowcaseListing(input: {
  categoryId: string;
  categoryName: string;
  subcategory?: string;
  index: number;
}): Listing {
  const key = `${input.categoryId}-generic-${input.index + 1}`;
  const subcategory = input.subcategory?.trim() || input.categoryName;
  return buildListing(
    {
      key,
      categoryId: input.categoryId,
      subcategory,
      title: `نموذج ${input.categoryName} — معرض تجريبي`,
      titleEnglish: `${input.categoryName} showcase example`,
      description: `إعلان توضيحي لقسم ${input.categoryName} حتى لا تظهر الصفحة فارغة.`,
      descriptionEnglish: `An illustrative listing for the ${input.categoryName} category so the page is not empty.`,
      price: 100,
      emirate: "دبي",
      city: "دبي",
      area: "وسط المدينة",
      condition: "used",
    },
    80 + input.index,
  );
}
