export {
  addRecentSearch,
  clearRecentSearches,
  clearSessionUser,
  deleteLocalListing,
  getFavorites,
  getLocalListingById,
  getLocalListings,
  getLocalListingsForSeller,
  getRecentSearches,
  getSavedSearches,
  getSessionUser,
  isFavoriteListing,
  removeSavedSearch,
  replaceSavedSearches,
  saveAccountProof,
  getAccountProof,
  saveCurrentSearch,
  saveLocalListing,
  setSessionUser,
  toggleFavorite,
  type FavoriteRecord,
  type SavedSearch,
} from "./client-storage";
